dotnet/Silk.NET

examples/BlankWindow/Program.cs
src/Windowing/Silk.NET.GLFW/Glfw.cs
src/Windowing/Silk.NET.GLFW/Interfaces/IGlfw.cs
src/Windowing/Silk.NET.Windowing.Common/WindowOptions.cs

Adds `GetProcAddress` to the GLFW bindings.
Also adds a missing license header, and removes an unnecessary using.
None.
None.

Add glfwGetProcAddress (+small changes)

---

documentation/proposals/Proposal - Input.md

This proposal covers the following areas:
- `Silk.NET.Input`
- `Silk.NET.Input.Common`
- `Silk.NET.Input.Desktop`
- `Silk.NET.Input.Mobile`
None.
None.

Proposal for a keyboard, mouse, and human input API

---

documentation/proposals/Proposal - Input.md
src/Input/Silk.NET.Input.Common/Axis.cs
src/Input/Silk.NET.Input.Common/Button.cs
src/Input/Silk.NET.Input.Common/Deadzone.cs
src/Input/Silk.NET.Input.Common/Enums/ButtonName.cs
src/Input/Silk.NET.Input.Common/Enums/DeadzoneMethod.cs
src/Input/Silk.NET.Input.Common/Enums/Key.cs
src/Input/Silk.NET.Input.Common/Enums/MouseButton.cs
src/Input/Silk.NET.Input.Common/Enums/Position2D.cs
src/Input/Silk.NET.Input.Common/Hat.cs
src/Input/Silk.NET.Input.Common/Interfaces/IGamepad.cs
src/Input/Silk.NET.Input.Common/Interfaces/IInputContext.cs
src/Input/Silk.NET.Input.Common/Interfaces/IInputDevice.cs
src/Input/Silk.NET.Input.Common/Interfaces/IInputPlatform.cs
src/Input/Silk.NET.Input.Common/Interfaces/IJoystick.cs
src/Input/Silk.NET.Input.Common/Interfaces/IKeyboard.cs
src/Input/Silk.NET.Input.Common/Interfaces/IMouse.cs
src/Input/Silk.NET.Input.Common/ScrollWheel.cs
src/Input/Silk.NET.Input.Common/Thumbstick.cs
src/Input/Silk.NET.Input.Common/Trigger.cs
src/Windowing/Silk.NET.GLFW/Enums/Keys.cs

Add documentation to Input.Common, as of right now everything is completely undocumented.
None.

Document Input.Common

---

src/Core/Silk.NET.Core/Loader/LibraryLoader.cs

Fixes `SymbolLoadingException`.
Links go here.
We wouldn't have encountered this if NVIDIA was actually compliant with the OpenGL 4.6 spec - `glPolygonOffsetClamp` wasn't implemented by driver 390. Will complain to them in my own time.

Use custom options on NativeLibraryBuilder

---

build/binder_bakery_info/GL-All.json
build/binder_specifications/GLES.json
examples/Triangle/Game.cs
src/Core/BuildTools/Bind/ProfileWriter.cs
src/Core/BuildTools/Common/Profile.cs
src/Core/BuildTools/Convert/Baking/ProfileBakery.cs
src/Core/BuildTools/Convert/Baking/ProfileBakeryInformation.cs
src/Core/BuildTools/Convert/Baking/ProfileBakeryInformationBuilder.cs
src/Core/Silk.NET.Core/Loader/LibraryLoader.cs
src/Core/Silk.NET.Core/Native/NativeAPI.cs
src/Core/Silk.NET.Core/Native/NativeExtension.cs
src/Core/Silk.NET.Core/Silk.NET.Core.csproj
src/OpenAL/Extensions/Silk.NET.OpenAL.Extensions.Enumeration/Silk.NET.OpenAL.Extensions.Enumeration.csproj
src/OpenAL/Silk.NET.OpenAL/AL/AL.cs
src/OpenAL/Silk.NET.OpenAL/AL/ALLoader.cs
src/OpenAL/Silk.NET.OpenAL/ALC/ALContext.cs
src/OpenGL/Silk.NET.OpenGL.Legacy/Silk.NET.OpenGL.Legacy.csproj
src/OpenGL/Silk.NET.OpenGL/Silk.NET.OpenGL.csproj
src/OpenGL/Silk.NET.OpenGLES/Silk.NET.OpenGLES.csproj
src/Windowing/Silk.NET.Windowing.Common/Interfaces/ISilkPlatform.cs
src/Windowing/Silk.NET.Windowing.Desktop/GlfwPlatform.cs
src/Windowing/Silk.NET.Windowing/SilkLoader.cs

- Adds a GetProcAddress method to `ISilkPlatform`
- Adds an `IPlatformLoader` which uses the `ISilkPlatform` to load symbols via ADL
- Adds a SymbolLoaderName property to the profile JSON and bakery JSON.
- Adds a static constructor to `NativeAPI`s
- Refactors LibraryLoader to use multiple `NativeLibraryBuilder`s.
- Closes #22 
#22

Use custom symbol loading

---

azure-pipelines.yml
build/props/common.props
src/Core/BuildTools/BuildTools.csproj
src/Core/BuildTools/GLXmlConvert/Construction/ParsingHelpers.cs

Updates Build Tools to .Net Core 3
Resolving any Issues
See #41 for further information

Build Tools .Net Core 3

---

documentation/proposals/Proposal - Window Hosts (Monitors).md

This PR introduces the concept of a "window host" to Silk.NET - an object on which windows can be created. More importantly, this proposal introduces monitor APIs (an example of a window host) and subwindows - where all windows are also window hosts.
Could be linked to #82 
- Discussion Point: do we want to call them Screens or Monitors?

Add a window hosts API for monitor management and subwindows.

---

documentation/proposals/Proposal - Views.md

This PR aims to iron out an API division between views and windows, the former containing only the core windowing APIs and the latter containing the rest. This is in an effort to ensure that we lay out a set of APIs that will ALWAYS be available on every platform we support, and there isn't a way we can do that in the current state of the windowing API.
#84

Strip down the core windowing APIs into a mobile-friendly "view" interface

---

src/Windowing/Silk.NET.Windowing.Desktop/GlfwWindow.cs

Replaced VSYNC sleep logic with an approach where the events are just not called until the time is right. This avoids many problems with frame rates and update rates.
Closes #93 
#94 
Testing seems to work as expected. Needs some testing for adaptive vsync.

Replaced vsync sleep logic

---

src/Lab/MonitorPlayground/MonitorPlayground.csproj
src/Windowing/Silk.NET.Windowing.Common/Interfaces/IMonitor.cs
src/Windowing/Silk.NET.Windowing.Desktop/GlfwMonitor.cs
src/Windowing/Silk.NET.Windowing.Desktop/GlfwWindow.cs

Adds the ability to get all of a monitor's video mode and gamma correction.
Closes #110 
GLFW primarily works with gamma ramps, not plain exponents. While it has a function to set gamma ramp via exponent, there doesn't seem to be a way to get that exponent *back* from GLFW. Because of this, we'll have to assume the default gamma is 1.0 when a monitor is first created. I don't know enough about monitors to know if that's going to be an issue or not.
Setting video modes will come in a later PR, GLFW implements this in a very odd way that makes it difficult to implement.

Monitor video modes and gamma correction

---

src/Windowing/Silk.NET.Windowing.Common/Interfaces/IView.cs
src/Windowing/Silk.NET.Windowing.Desktop/GlfwWindow.cs

As a follow up to the recent changes allowing a window to be event-driven, this change allows another thread to post an empty message to the event queue to wake up the main thread.
Current
Discussed wtih @Perksey on Discord

Wrapping Glfw's PostEmptyEvent method

---

src/Windowing/Silk.NET.Windowing.Desktop/GlfwWindow.cs

Stabilizes the Update/Render limiters, ie. when the FPS drops below the desired amount, then the update period gets decreased accordingly in hopes that the sudden drop gets compensated for. 
current release

stabilization of update/FPS limiting

---

src/Maths/Silk.NET.Maths/Box2.cs
src/Maths/Silk.NET.Maths/Box3.cs
src/Maths/Silk.NET.Maths/Scalar.cs

Box2<T> Box3<T>

---

src/Maths/Silk.NET.Maths/Vector2.cs
src/Maths/Silk.NET.Maths/Vector3.cs
src/Maths/Silk.NET.Maths/Vector4.cs

Simply making Vector2/3/4<T> `readonly` and removing the only non-readonly method `Normalize()` (also adds `WithX/Y/Z/W`)

Readonly Vectors

---

examples/CSharp/Tutorial 1.1 - Hello Window/Tutorial 1.1 - Hello Window.csproj
examples/CSharp/Tutorial 1.2 - Hello quad/Program.cs
examples/CSharp/Tutorial 1.2 - Hello quad/Tutorial 1.2 - Hello quad.csproj
examples/CSharp/Tutorial 1.3 - Abstractions/Program.cs
examples/CSharp/Tutorial 1.3 - Abstractions/Tutorial 1.3 - Abstraction.csproj
examples/CSharp/Tutorial 1.4 - Textures/Program.cs
examples/CSharp/Tutorial 1.4 - Textures/Texture.cs
examples/CSharp/Tutorial 1.4 - Textures/Tutorial 1.4 - Textures.csproj
examples/CSharp/Tutorial 1.5 - Transformations/Program.cs
examples/CSharp/Tutorial 1.5 - Transformations/Texture.cs
examples/CSharp/Tutorial 1.5 - Transformations/Tutorial 1.5 - Transformations.csproj
src/Core/Silk.NET.Core/Silk.NET.Core.csproj

Updates method calls in example projects to use non-deprecated versions of the method calls.
[#210 - Examples still use obsolete APIs](https://github.com/Ultz/Silk.NET/issues/210)

#210 - Start of updating obsolete methods in example projects

---

src/Lab/BlankWindow/BlankWindow.csproj
src/Lab/BlankWindow/Program.cs

BlankWindow Lab is still using the beta version of ImageSharp where every other project has been updated to use rc3, ideally we would use the same version of the nuget package across the solution.

Consolidate the use of ImageSharp rc3 in BlankWindow Lab

---

src/Core/Silk.NET.Core/Core1.0/Loader/GLSymbolLoader.cs

Fixes the first chance exceptions some users get (for good this time)
None that I know of
This PR was done in my phone in GitHub web so I apologise if something went wrong.

Update GLSymbolLoader to use the new, non-throwing load methods

---

azure-pipelines-cd.yml
azure-pipelines.yml
global.json

Update CI to .Net 5 Preview 6
Also, create a `global.json`
See #236 for master update to `3.1.302` this will cause a merge conflict eventually if both are merged.

.Net 5 Preview 6

---

src/Windowing/Silk.NET.GLFW/GlfwProvider.cs

Checks the result of Glfw.Init, retrieves any error and throws instead of continuing.
#267 : Glfw.Init / glfwInit can fail silently
...

Throw exception when Glfw.Init fails.

---

.github/workflows/build.yml
.github/workflows/deploy.yml
global.json
src/Windowing/Silk.NET.GLFW/Glfw.cs
src/Windowing/Silk.NET.GLFW/GlfwProvider.cs

Corrects Glfw.GetError parameter type.
Updates GlfwProvider static initializer to handle UTF8.
Introduced as non-breaking obsoleted change to API.
Breaking when obsolete method removed, targeting v2.0.
Discord discussions:
* [Meant to be out byte*, UTF8](https://discordapp.com/channels/521092042781229087/607634593201520651/743984606704959499)
* [Duplicate the endpoint and add [Obsolete] to prevent breaking change in master](https://discordapp.com/channels/521092042781229087/607634593201520651/743996982934241301)
* [Fix CI conditionals](https://discordapp.com/channels/521092042781229087/607634593201520651/743998958363213924)
* [Keep CI steps separate instead of merging](https://discordapp.com/channels/521092042781229087/607634593201520651/744000671669551192)
CI adjusted to skip setting up …

Glfw.GetError has wrong parameter type (char* -> byte*)

---

examples/CSharp/Tutorial 1.2 - Hello quad/Program.cs
examples/CSharp/Tutorial 1.3 - Abstractions/Shader.cs
examples/CSharp/Tutorial 1.4 - Textures/Shader.cs
examples/CSharp/Tutorial 1.5 - Transformations/Shader.cs
examples/CSharp/Tutorial 2.1 - Co-ordinate Systems/Shader.cs
examples/CSharp/Tutorial 2.2 - Camera/Shader.cs
examples/CSharp/Tutorial 3.1 - Ambient Lighting/Shader.cs
examples/CSharp/Tutorial 3.2 - Diffuse Lighting/Shader.cs
examples/CSharp/Tutorial 3.3 - Specular Lighting/Shader.cs
examples/CSharp/Tutorial 3.4 - Materials/Shader.cs
examples/CSharp/Tutorial 3.5 - Lighting Maps/Shader.cs

Previously, we were throwing an exception if any info log was posted by the GL driver, which means we were throwing for non-breaking warnings. This PR changes the tutorials to use glGetProgram to determine if linking was successful before throwing any exceptions.
Closes #270 
cc @RhysWhy for future tutorials

Fix exceptions being thrown when there is no error in the tutorials

---

.github/workflows/maths-ci.yml
.github/workflows/maths-jit-diff.yml
build/maths/windows-jit-asm-x64
build/maths/windows-jit-asm-x86
src/Lab/GenericMaths/GenericMaths.csproj
src/Lab/GenericMaths/Program.cs
src/Maths/Silk.NET.Maths.GenericsGenerator/Abstractions.cs
src/Maths/Silk.NET.Maths.GenericsGenerator/Generator.cs
src/Maths/Silk.NET.Maths.GenericsGenerator/OperationWalker.cs
src/Maths/Silk.NET.Maths.GenericsGenerator/ValueTypes/BinaryOperatorValue.cs
src/Maths/Silk.NET.Maths.GenericsGenerator/ValueTypes/FieldReferenceValue.cs
src/Maths/Silk.NET.Maths.GenericsGenerator/ValueTypes/LiteralValue.cs
src/Maths/Silk.NET.Maths.GenericsGenerator/ValueTypes/LocalReferenceValue.cs
src/Maths/Silk.NET.Maths.GenericsGenerator/ValueTypes/ParameterReferenceValue.cs
src/Maths/Silk.NET.Maths.GenericsGenerator/ValueTypes/PropertyReferenceValue.cs
src/Maths/Silk.NET.Maths.GenericsGenerator/ValueTypes/UnaryOperatorValue.cs

This PR will introduce Type specialization, which will transform code like:
```cs
public struct TypeSpecialization
{
public float Field;
public float Property { get; set; }
public float Method()
{
var a = Field + Property;
var b = 5 + 5;
var c = a + b;
return c * c;
}
}
```
into
```cs
public struct TypeSpecialization<T> where T : unmanaged
{
public T Field;
public T Property { get; set; }
public T Method()
{
if (typeof(T) == typeof(byte)) return (byte)(object)((TypeSpecialization_Byte)(object)this).Method();
else if ...
}
}
public struct TypeSpecialization_Byte
{
public byte Field;
public byte Property { get; set; }
public byte Method()
{
// same code produced when specializing just that method for byte.
}
}
```
In a future PR options will be introduced for both types and methods to not …

Type Specialization

---

src/Maths/Silk.NET.Maths.GenericsGenerator/Generator.cs

This PR introduces the capability to generate a generic "helper" type for specialized types like so:
From:
```cs
[GenericMaths]
public struct TypeSpecialization
{
public float Field;
public float Property { get; set; }
public float Method()
{
var a = Field + Property;
var b = 5 + 5;
var c = a + b;
return c * c;
}
}
```
to
```cs
public struct TypeSpecialization<T> where T : unmanaged
{
public T Field;
public T Property { get; set; }
private void ThrowHelper() => throw new InvalidOperationException("..."); // Name is of course UB
public T Method()
{
if (typeof(T) == typeof(byte)) return Method_S_Byte();
// ...
else if (typeof(T) == typeof(double)) return Method_S_Double();
else { ThrowHelper(); return default(T); }
}
// Specialized methods
}
```

[WIP] Generic Type generalization

---

.editorconfig
src/Core/Silk.NET.Core/Loader/LibraryLoader.cs
src/Core/Silk.NET.Core/Native/GlobalMemory.cs
src/Core/Silk.NET.Core/Native/NativeStringEncoding.cs
src/Core/Silk.NET.Core/Native/SilkMarshal.cs
src/Core/Silk.NET.Core/Native/UnmanagedType.cs
src/Core/Silk.NET.Core/Silk.NET.Core.csproj

Adds a new, richer set of APIs to Silk.NET.Core.Native including an abstraction over HGlobal and pinned object heaps, as well as support for UTF8 strings on .NET Standard 2.0.
The older methods have been deprecated but not removed yet, as they are still used by BuildTools.

SilkMarshal 2.0

---

.vscode/launch.json
.vscode/tasks.json

Fixes: #273
Adding tasks and launch configurations to allow running and debugging
tutorial projects directly from Visual Studio Code.
Newly added tasks also allow publishing tutorial projects and running
them under under the wather.
Verification:
- Ran each added launch configuration from VS Code
- Published a couple projects and made sure artificats were written to
the expected location
- Ran a couple projects under the watcher

Add VS Code support for tutorials

---

src/OpenGL/Silk.NET.OpenGL/GL.cs

Documentation for the `GL.cs` (non-gen) class, providing remarks where necessary and direct links to the relevant Khronos documentation for the wrapped method.
As far as I know, there's not a way to document the (generated) `GL.gen.cs`. I'm willing to document all of the members within that generated file, awaiting the relevant functionality for documenting generated `.cs` files.
***Remark:** It's possible my code-cleanup has interfered with the Silk.NET code styling conventions, and if so I'm willing to also make the necessary modifications to ensure that code style is maintained.*

GL.cs (non-gen) documentation

---

src/Lab/VulkanTriangle/HelloTriangleApplication.cs

1. Use TryGetInstanceExtension instead of deprecated TryGetExtension (fixed #349)
2. Moved _vkSwapchain initialization to CreateSwapChain()
3. Fixed out of bounds issue when iterating over presentModes

Fixed issues in VulkanTriangle Demo

---

.github/workflows/build.yml
build/nuke/Build.cs
src/OpenGL/Silk.NET.OpenGL/GL.cs

[2.0] Fix the experimental feed

---

src/Lab/VulkanTriangle/HelloTriangleApplication.cs
src/OpenXR/Silk.NET.OpenXR/XR.cs
src/Vulkan/Silk.NET.Vulkan/Vk.cs

Updates `Vk` and `XR` classes to improve thread-safety, performance, and memory utilisation, whilst also removing a bug which would cause an 'infinite' loop when the number of extension properties exceeded 128.
Also adds `Vk.GetPhysicalDevices` to retrieve the cache of physical devices for an instance.
Updated `VulkanTriangles` to leverage API changes, and to review stack allocations.
The `VulkanTriangles` project was broken when accessing a device that had >128 extensions and would enter an 'infinite' loop allocating increasing amounts of memory until the application crashed.  It was also allocating large data structures (>1k) on the stack, which risksed stack overflows.
The resultant fixes re-worked the areas that caused these problems and are based on discussions on Discord.
A full …

Bug fixes and Improvements to Vk and XR.

---

src/Core/Silk.NET.SilkTouch/Middlewares/InjectMiddleware.cs

The existing code scans all code repeatedly for multiple strings, notably `%$RESULT$%` and `%$PARAM(name)$%` (x number of parameters).
This code (to be tested), will scan the string once, finding all examples of the above and doing substitutions only as needed.  As such it should be orders of magnitude faster.

nints and start of Vulkan Function Tables (closes #387)

---

src/Windowing/Silk.NET.Windowing.Common/Internals/ViewImplementationBase.cs

Fixes issue #394.
In summary, the stopwatches need to be restarted _before_ the events are invoked. Or really, stopwatches need to be restarted right after the elapsed time was taken. Otherwise, the time the invocation of the method took (and therefore the whole update/render logic the library user wrote) will not be counted as elapsed time on the next invocation.
If you store a double time that starts at 0 and each update add to it the elapsed time parameter, you'd now get nearly exactly the same as if you just used a stopwatch that was started on load, even if your Update method takes a very long time. Before this change, you'd see that your time variable would stay behind (this might not have been noticeable if your Update method is very fast).

Fix elapsed time parameters on Window.Render and Update events

---

src/Windowing/Silk.NET.SDL/SdlContext.cs
src/Windowing/Silk.NET.SDL/SdlNativeWindow.cs
src/Windowing/Silk.NET.SDL/SdlProvider.cs
src/Windowing/Silk.NET.Windowing.Sdl/SdlView.cs
src/Windowing/Silk.NET.Windowing.Sdl/SdlWindowing.cs

Only call:
https://github.com/dotnet/Silk.NET/blob/3bd07365dde27da14d64e7f1db8fc3797a55ec4a/src/Windowing/Silk.NET.SDL/SDL.cs#L898
When preceding call reports failure(when possible).
This PR fixes:
`Silk.NET.SDL.SdlException: Failed loading udev_device_get_action: /home/dinolek/Desktop/Silk.NET/src/Lab/VulkanTriangle/bin/Debug/netcoreapp3.1/runtimes/linux-x64/native/libSDL2-2.0.so: undefined symbol: _udev_device_get_action`

Check for sdl errors only when failed

---

src/Input/Silk.NET.Input.Sdl/SdlGamepad.cs

Support the deadzone feature in Silk.NET.Input.Sdl
Specifically, application of the Deadzone object to SdlGamepad
SdlGamepad has a Deadzone object, however the deadzone is not applied in SdlGamepad DoEvent method.
This prevents the SdlGamepad DoEvent method from filtering out superfluous ThumbstickMoved events on idle.
This may also cause unwanted thumbstick drift.
~**This fix is untested!**~
~Due to environmental factors and my general unfamiliarity with the project dependency tree, I was unable to run this fix to verify its suitability. It does, however, compile.~
Edit: Testing done after creating sister PR here: https://github.com/dotnet/Silk.NET/pull/452
1) I have made the assumption the SdlGamepad._thumbsticks array is not modified elsewhere, since it is private. This means that it …

apply deadzone to sdl gamepad

---

README.md

Remove the "from" part of the team README section

---

src/Windowing/Silk.NET.Windowing.Sdl/SdlView.cs

Fixes an exception when initializing the SDL view on Vulkan. Caused by lack of appropriate API checks. Closes #490

Fix missing API checks in SdlView

---

src/Lab/Experiments/VulkanTriangle/HelloTriangleApplication.cs
src/Windowing/Silk.NET.Windowing.Sdl/SdlView.cs

Fix console error spam in the VulkanTriangle project due to an invalid swap chain being created when an SDL window is minimized. Closes #492 
Closes #499

Fix Vulkan validation layer errors when minimizing SDL window

---

src/Core/Silk.NET.Core/Loader/LibraryLoader.cs

The FileNotFound exceptions only provide a message but it would be nice if they also provide the filename they couldn't found in the FileName property. This is nice for creating own error messages.
A recent usage was that OpenAL32.dll was missing because it wasn't installed. But as it happens inside a game with a graphical UI I prefer to show a very short notice about the missing DLL rather then the long message provided by Silk.NET.
Moreover the name can be better parsed if it is provided on its own and someone could create more user-friendly messages like "OpenAL is not installed" from such exception more easily.
The changes should be small and safe.

Start of improving FileNotFound exceptions

---

src/Native/Directory.Build.targets
src/Native/Silk.NET.Assimp.Native/Silk.NET.Assimp.Native.csproj
src/Native/Silk.NET.GLFW.Native/Silk.NET.GLFW.Native.csproj
src/Native/Silk.NET.OpenAL.Soft.Native/Silk.NET.OpenAL.Soft.Native.csproj
src/Native/Silk.NET.SDL.Native/Silk.NET.SDL.Native.csproj

Fixes #514.
This resolves `NU5127` and `NU5128` at pack time. Also verified using a local package source that `NU1701` no longer occurs when consuming the package.
New versions of all the native packages should probably be pushed after this is merged.

Fix `NU5127`, `NU5128`, and `NU1701` in relation to native packages.

---

generator.json
src/OpenCL/Silk.NET.OpenCL/OpenCLLibraryNameContainer.cs

This fixes a problem on linux where I had to create a link named libOpenCL.so manually and point it to libOpenCL.so.1
Fixed as discussed here: https://discord.com/channels/521092042781229087/607634593201520651/854308234578755584

Fix lib open cl so linkname on linux

---

documentation/proposals/Proposal - Enhanced Input Events.md

Adds missing input functionality, as discussed in Discord and in issue #399

Enhanced Input Events

---

src/Lab/Experiments/CoreRTTest/CoreRTTest.csproj

Upgrade to the latest AOT compiler.
The native aot compiler has been greatly improved, also the 1.0.0-alpha version of CoreRT has been deprecated.

Upgrade to the latest AOT compiler

---

documentation/proposals/Proposal - Multi-Backend Input.md

This enables input to use multiple backends (i.e. so we can have windowing-based input as well as something like OpenXR) and contains other refactorings for 3.0.
Unlike previous 3.0 proposals this proposes only a minor change of the public API.

Multi-Backend Input for Silk.NET 3.0

---

documentation/proposals/Proposal - 3.0 & 3.X Software Development Plan.md

This creates a roadmap and basic software development plan for 3.0, as well as a support & breaking change policy after the initial 3.0.

3.0 Software Development Plan

---

src/Assimp/Silk.NET.Assimp/Assimp.cs
src/Core/Silk.NET.Core/Native/NativeApiAttribute.cs
src/Core/Silk.NET.Core/Native/SilkMarshal.cs
src/Core/Silk.NET.SilkTouch/MarshalContext.cs
src/Core/Silk.NET.SilkTouch/NativeApiGenerator.cs

2.7 is due today, to get this fix in we'll delay release to tomorrow.
This implements support for platform-default P/Invoke calling conventions instead of blindly using Cdecl (which is incorrect!) This is something that was pointed out when SilkTouch development first started, but was not implemented.
On .NET Standard 2.0, seeing as there's no true way to specify "platform default" we use a "best effort" implementation to cover known cases. Right now, this is just 32-bit Windows being not Cdecl - there are no other concerns we know of today.
Codegen:
- [Assimp.WinapiNET5.gen.txt](https://github.com/dotnet/Silk.NET/files/6948095/Assimp.WinapiNET5.gen.txt)
- [Assimp.WinapiNS20.gen.txt](https://github.com/dotnet/Silk.NET/files/6948096/Assimp.WinapiNS20.gen.txt)

"Winapi" support on NS20 and .NET 5

---

.github/workflows/deploy.yml
build/nuke/Build.cs

It looks like the .NET Foundation code signing service doesn't cope well under pressure, so I've now made it do things a lot more slowly by starting a process for each individual package rather than signing all packages at once (with a degree of parallelism)

Code signing issues "workaround"

---

src/Windowing/Silk.NET.Windowing.Glfw/GlfwWindow.cs

Fixes Calling window.Close before window.Run causing an exception on GLFW.
Closes #565

Fix calling SetWindowShouldClose if _glfwWindow is null

---

src/Windowing/Silk.NET.Windowing.Common/Structs/WindowOptions.cs

`WindowOptions.Size` and `SharedContext` had an extra `cref`, causing them to show the documentation meant for `IWindowProperties`.

Fix incorrect documentation in WindowOptions

---

src/Input/Silk.NET.Input.Common/Structs/Thumbstick.cs

Math.Atan2 returns value in radians, not degrees.

Fix incorrect documentation in Thumbstick.Direction

---

src/Maths/Silk.NET.Maths/Box2D.cs
src/Maths/Silk.NET.Maths/Box3D.cs

`Box2D.Center` and `Box3D.Center` were calculated falsely. Fix that.
Also check other classes in Maths for similar problems.
The issue: https://github.com/dotnet/Silk.NET/issues/567

fix Box2D.Center returns bogus values

---

src/Windowing/Silk.NET.Windowing.Sdl/SdlView.cs

Not a breaking change seeing as the defaults are undefined anyway.

Change the SDL default bits to be more sensible

---

examples/CSharp/OpenGL Tutorials/Tutorial 3.5 - Lighting Maps/Program.cs

Also fixing a comment to say texture 1 instead of texture 10

OpenGL Tutorial 3.5: Dispose SpecularMap

---

src/Windowing/Silk.NET.Windowing.Common/WindowExtensions.cs

DoRender was always called after DoUpdate, even if window was requested to close. This could cause an exception, for example if Graphics resource disposing was set to happen on the Closing-event.

Fix DoRender being called if Window.Close was called during DoUpdate

---

src/Input/Silk.NET.Input.Common/InputWindowExtensions.cs
src/Windowing/Silk.NET.Windowing.Common/Interfaces/IView.cs
src/Windowing/Silk.NET.Windowing.Common/Internals/ViewImplementationBase.cs

- Added an `IsInitialized` property to `IView`
- Changed `IsInitialized` property visibility in `ViewImplementationBase`  to `public `with `protected set`.
- `InputWindowExtensions.CreateInput` now throws an `InvalidOperationException` if `IsInitialized` returns `false`.
https://github.com/dotnet/Silk.NET/issues/591

#591 Add validation preventing System.AccessViolationException when using CreateInput on uninitialized views

---

src/Maths/Silk.NET.Maths/Matrix2X2.cs
src/Maths/Silk.NET.Maths/Matrix2X3.cs
src/Maths/Silk.NET.Maths/Matrix2X4.cs
src/Maths/Silk.NET.Maths/Matrix3X2.cs
src/Maths/Silk.NET.Maths/Matrix3X3.cs
src/Maths/Silk.NET.Maths/Matrix3X4.cs
src/Maths/Silk.NET.Maths/Matrix4X2.cs
src/Maths/Silk.NET.Maths/Matrix4X3.cs
src/Maths/Silk.NET.Maths/Matrix4X4.cs
src/Maths/Silk.NET.Maths/Scalar.MathFPort.cs
src/Maths/Silk.NET.Maths/Vector2D.cs
src/Maths/Silk.NET.Maths/Vector3D.cs
src/Maths/Silk.NET.Maths/Vector4D.cs

- Fixed the documentation comments where the description did not match the actual arguments e.g. for matrix sizes.
- Added  `<see cref="..."/>`tags for consistency as some methods had them but others did not.

Update doc comments for some Maths classes

---

src/Vulkan/VMASharp_OriginalSources/Allocation.cs
src/Vulkan/VMASharp_OriginalSources/AllocatorEnums.cs
src/Vulkan/VMASharp_OriginalSources/AllocatorStructs.cs
src/Vulkan/VMASharp_OriginalSources/BlockAllocation.cs
src/Vulkan/VMASharp_OriginalSources/BlockList.cs
src/Vulkan/VMASharp_OriginalSources/Budget.cs
src/Vulkan/VMASharp_OriginalSources/DedicatedAllocation.cs
src/Vulkan/VMASharp_OriginalSources/Defragmentation/BlockListDefragmentationContext.cs
src/Vulkan/VMASharp_OriginalSources/Defragmentation/DefragmentationAlgorithm.cs
src/Vulkan/VMASharp_OriginalSources/Defragmentation/DefragmentationContext.cs
src/Vulkan/VMASharp_OriginalSources/Defragmentation/FastDefragAlgorithm.cs
src/Vulkan/VMASharp_OriginalSources/Defragmentation/GenericDefragAlgorithm.cs
src/Vulkan/VMASharp_OriginalSources/Defragmentation/Structures.cs
src/Vulkan/VMASharp_OriginalSources/Exceptions.cs
src/Vulkan/VMASharp_OriginalSources/Helpers.cs
src/Vulkan/VMASharp_OriginalSources/Metadata/BlockMetadata_Generic.cs
src/Vulkan/VMASharp_OriginalSources/Metadata/IBlockMetadata.cs
src/Vulkan/VMASharp_OriginalSources/Stats.cs
src/Vulkan/VMASharp_OriginalSources/Suballocation.cs
src/Vulkan/VMASharp_OriginalSources/VulkanMemoryAllocator.cs
src/Vulkan/VMASharp_OriginalSources/VulkanMemoryBlock.cs
src/Vulkan/VMASharp_OriginalSources/VulkanMemoryPool.cs

Upload of VMASharp
Ported and C#ified, but without the data structure allocation optimizations of the original.

VMA Sources

---

src/OpenAL/Silk.NET.OpenAL/AL/AL.cs
src/OpenAL/Silk.NET.OpenAL/ALC/ALContext.cs
src/OpenAL/Silk.NET.OpenAL/Extensions/ALExtensionLoader.cs

This PR adds `TryGetExtension` methods to `AL` and `ALContext` classes in `Silk.NET.OpenAL`
https://github.com/dotnet/Silk.NET/issues/574
`TryGetExtension` method in `AL` is nearly the same as in OpenGL bindings. It was trivial to copy-paste and then compare to `GetExtension` to verify. The XML documentation was also taken from `GL` and modified.
However, `GetExtension` method in `ALContext` is different and also it doesn't use `ExtensionAttribute`. Also it requires a pointer to a `Device `to operate. So I am not sure if "copy-paste" approach would work. Should I convert `ALContext.GetExtension` to `TryGetExtension`?
Or maybe I am wrong, and it will be enough to copy existing method and import  `Silk.NET.Core.Attributes` namespace?
Just want to be sure.

Add TryGetExtension methods to AL & ALContext

---

src/Core/Silk.NET.Core/Miscellaneous/PfnVoidFunction.cs
src/OpenXR/Silk.NET.OpenXR/PfnDebugUtilsMessengerCallbackEXT.cs
src/Vulkan/Silk.NET.Vulkan/PfnAllocationFunction.cs
src/Vulkan/Silk.NET.Vulkan/PfnDebugReportCallbackEXT.cs
src/Vulkan/Silk.NET.Vulkan/PfnDebugUtilsMessengerCallbackEXT.cs
src/Vulkan/Silk.NET.Vulkan/PfnDeviceMemoryReportCallbackEXT.cs
src/Vulkan/Silk.NET.Vulkan/PfnFreeFunction.cs
src/Vulkan/Silk.NET.Vulkan/PfnInternalAllocationNotification.cs
src/Vulkan/Silk.NET.Vulkan/PfnInternalFreeNotification.cs
src/Vulkan/Silk.NET.Vulkan/PfnReallocationFunction.cs

Adding the IDisposable interface as it is implemented for the generated PFN structs (see StructWriter)

Add IDisposable call to SilkMarshall.Free for all PFN-structs

---

src/Windowing/Silk.NET.Windowing.Common/Interfaces/IViewProperties.cs
src/Windowing/Silk.NET.Windowing.Common/Internals/ViewImplementationBase.cs
src/Windowing/Silk.NET.Windowing.Common/Structs/ViewOptions.cs
src/Windowing/Silk.NET.Windowing.Common/Structs/WindowOptions.cs
src/Windowing/Silk.NET.Windowing.Glfw/GlfwWindow.cs
src/Windowing/Silk.NET.Windowing.Sdl/SdlView.cs

Implemented multisample support for the window's framebuffer, as highlighted in issue #641.

Add a Samples window option

---

documentation/proposals/Proposal - Vectorization - SIMD.md

Some methods in the prop operating on two arguments for some reason had the second argument as just `T` whereas it should be Vector<T>, I think.

Changes to the math simd proposal

---

src/Maths/Silk.NET.Maths.Tests/Scalar.Bitwise.cs
src/Maths/Silk.NET.Maths/Scalar.Bitwise/Scalar.And.cs
src/Maths/Silk.NET.Maths/Scalar.Bitwise/Scalar.Not.cs
src/Maths/Silk.NET.Maths/Scalar.Bitwise/Scalar.Or.cs
src/Maths/Silk.NET.Maths/Scalar.Bitwise/Scalar.RotateLeft.cs
src/Maths/Silk.NET.Maths/Scalar.Bitwise/Scalar.RotateRight.cs
src/Maths/Silk.NET.Maths/Scalar.Bitwise/Scalar.ShiftLeft.cs
src/Maths/Silk.NET.Maths/Scalar.Bitwise/Scalar.ShiftRight.cs
src/Maths/Silk.NET.Maths/Scalar.Bitwise/Scalar.Xor.cs

Implements [proposal](https://github.com/dotnet/Silk.NET/blob/main/documentation/proposals/Proposal%20-%20Bitwise%20-%20Scalar.md)

Scalar bitwise implementation

---

.github/workflows/build.yml

I intentionally only wrote down just two: those are assumed to change often. We could add all files which don't affect the build to it, but imo it makes maintaining this thing harder.

No need to run CI on source-unrelated files

---

src/Windowing/Silk.NET.Windowing.Common/Interfaces/IWindowProperties.cs
src/Windowing/Silk.NET.Windowing.Common/Internals/WindowImplementationBase.cs
src/Windowing/Silk.NET.Windowing.Common/Structs/WindowOptions.cs
src/Windowing/Silk.NET.Windowing.Common/Window.cs
src/Windowing/Silk.NET.Windowing.Glfw/GlfwWindow.cs
src/Windowing/Silk.NET.Windowing.Sdl/SdlWindow.cs

Adds the possibility to specify an optional window class for a window. Systems like X11 use the window class to store settings for specific applications. Glfw defaults the window class to the window title which is not always wanted. Especially with version numbers in the title this causes problems as a window class should stay the same for the same application.

start of adding window class option

---

.github/workflows/publish-site.yml

Apparently the CI token can't push anymore so let's use the same one the rewrite merger pipeline uses...

Fix website build pipeline

---

src/Core/Silk.NET.Core/Native/IVTable.cs
src/Core/Silk.NET.SilkTouch/NativeApiGenerator.cs
src/Core/Silk.NET.SilkTouch/VTableGeneration.cs
src/Vulkan/Silk.NET.Vulkan/Vk.cs

Popped up while looking at the Stride migration, which has a graphics abstraction that can create multiple devices but only ever has one instance: let's just reuse the instance functions we've already loaded!
Considering our (my) advice is to have one object for each instance-device combination, this is quite a nice-to-have but at the same time a niche one so if you're not comfortable with it that's fine.

Add support for cloning Vk objects to reuse their function tables independently

---

generator.json
src/Core/Silk.NET.Core/Loader/DefaultPathResolver.cs
src/Vulkan/Silk.NET.Vulkan/VulkanLibraryNameContainer.cs

Fixed name of the Vulkan loader library on Android (changed from "libvulkan.so.1" to "libvulkan.so") - see [https://source.android.com/devices/graphics/implement-vulkan](https://source.android.com/devices/graphics/implement-vulkan) "Vulkan loader" section that this is the officially correct name of the library.
With this change the Vk.GetApi will load the library successfully without any additional magic from the path resolver.
But even with using the "libvulkan.so.1" name, the path resolved that is used in Silk.Net could correctly resolve the library name in the GetLinuxPossibilities method that would strip the ending ".1" and this will lead to the correct library name.
But this does not happen because a null reference exception is thrown before the GetLinuxPossibilities is called. This …

Fixed loading Vulkan loader on Android (.Net 6)

---

src/OpenGL/Extensions/Silk.NET.OpenGL.Extensions.ImGui/ImGuiController.cs

Add a custom constructor for `ImGuiController`, so user can configure the ImGui before the first frame.
The pain is the following. 
- I needed a Docking feature of ImGui, which is being enabled with the next code:
```csharp
var io = ImGui.GetIO();
io.ConfigFlags |= ImGuiConfigFlags.DockingEnable;
```
If I set the config flag before calling the constructor - exception (ImGui is not yet initialized)
If I set the config flag after the constructor - my docking configuration is reset (because of new frame has begun without a flag)
- I also needed to load many custom fonts, which is most conviniently can be done before the first frame, so that ImGui can bake the font texture. The code is as follows:
```csharp
var io = ImGui.GetIO();
io.Fonts.AddFontFromFileTTF("path/to/font.ttf", 24);
```
Both …

Create custom ImGuiController constructor with onConfigureAction

---

src/Windowing/Silk.NET.Windowing.Common/Internals/ViewImplementationBase.cs

Noticed this when adding a Silk.NET backend to Trains.NET.

Fix a small divide by zero error in PointToFramebuffer

---

src/Input/Silk.NET.Input.Common/Internals/InputContextImplementationBase.cs
src/Input/Silk.NET.Input.Glfw/GlfwInputContext.cs
src/Input/Silk.NET.Input.Sdl/SdlInputContext.cs
src/Windowing/Silk.NET.Windowing.Common/Internals/ViewImplementationBase.cs
src/Windowing/Silk.NET.Windowing.Common/Silk.NET.Windowing.Common.csproj
src/Windowing/Silk.NET.Windowing.Sdl/SdlView.cs

Update input context in DoEvents instead of DoUpdate

---

src/Input/Silk.NET.Input.Common/Structs/ScrollWheel.cs
src/Input/Silk.NET.Input.Sdl/SdlMouse.cs

This is in line with equivalent logic in `GlfwMouse`.
Previously, wheel data was only updated when the `SdlMouse` `Scroll` event was invoked. Additionally, the scroll wheels data was never reset which lead to incorrect scrolling behavior.
This CL also adds an `IEquatable<ScrollWheel>` implementation to the `ScrollWheel` struct so we can value-compare instances without casting the underlying data to `System.Numerics.Vector2`.
1. Validate correct behavior when using the standard GLfw backend:
- Open the Silk.NET solution and compile the `Examples/CSharp/OpenGL Demos/ImGui` example project.
- Run the `Examples/CSharp/OpenGL Demos/ImGui` example project.
- Open the `Child windows` section from the `Layout & Scrolling` section of the ImGui demo window.
- Position the mouse cursor over the …

Ensure that the SDL mouse wheel is updated

---

.github/workflows/GLFW.yml
.gitmodules
build/nuke/Build.Native.cs
build/nuke/Build.Support.cs

Self building GLFW for Windows, Mac and Linux, including Mac arm64.
This partially resolves #727.
https://discord.com/channels/521092042781229087/587346162802229298/936229014249562172
Currently the mac libraries cause a security warning, since they are not signed. This needs to be resolved before shipping them.
Silk is also still missing arm64 build for OpenAL, and ImGUI.NET also does not ship with arm natives.

Add native GLFW binary builds

---

src/Core/Silk.NET.Core/Native/SilkMarshal.cs

```cs
var ptr = Silk.NET.Core.Native.SilkMarshal.StringToPtr("ä", Silk.NET.Core.Native.NativeStringEncoding.Ansi);
```
Threw `The output byte buffer is too small to contain the encoded data`
GetMaxSizeOf did not include a null terminator byte for Ansi/LPStr strings, which then caused StringIntoSpan to fail.

Fix SilkMarshal.GetMaxSizeOf not including space for null terminator for NativeStringEncoding.LPStr

---

src/Windowing/Silk.NET.Windowing.Glfw/GlfwWindow.cs

Set the callbacks in GlfwWindow to null after unregistering so the originally registered methods are released.
This addresses part of #821 
My current understanding is that the registered callbacks are closures that capture the window itself. This creates a kind of circular reference that seems to prevent the window from being released by the GC.

set callbacks on GlfwWindow to null after unregistering

---

Silk.NET.sln
src/OpenGL/Extensions/Silk.NET.OpenGL.Extensions.ImGui/ImGuiController.cs
src/OpenGL/Extensions/Silk.NET.OpenGL.Extensions.ImGui/ImGuiFontConfig.cs
src/OpenGL/Extensions/Silk.NET.OpenGL.Extensions.ImGui/Shader.cs
src/OpenGL/Extensions/Silk.NET.OpenGL.Extensions.ImGui/Texture.cs
src/OpenGL/Extensions/Silk.NET.OpenGL.Extensions.ImGui/Util.cs
src/OpenGL/Extensions/Silk.NET.OpenGL.Legacy.Extensions.ImGui/PublicAPI/net5.0/PublicAPI.Shipped.txt
src/OpenGL/Extensions/Silk.NET.OpenGL.Legacy.Extensions.ImGui/PublicAPI/net5.0/PublicAPI.Unshipped.txt
src/OpenGL/Extensions/Silk.NET.OpenGL.Legacy.Extensions.ImGui/PublicAPI/netcoreapp3.1/PublicAPI.Shipped.txt
src/OpenGL/Extensions/Silk.NET.OpenGL.Legacy.Extensions.ImGui/PublicAPI/netcoreapp3.1/PublicAPI.Unshipped.txt
src/OpenGL/Extensions/Silk.NET.OpenGL.Legacy.Extensions.ImGui/PublicAPI/netstandard2.0/PublicAPI.Shipped.txt
src/OpenGL/Extensions/Silk.NET.OpenGL.Legacy.Extensions.ImGui/PublicAPI/netstandard2.0/PublicAPI.Unshipped.txt
src/OpenGL/Extensions/Silk.NET.OpenGL.Legacy.Extensions.ImGui/PublicAPI/netstandard2.1/PublicAPI.Shipped.txt
src/OpenGL/Extensions/Silk.NET.OpenGL.Legacy.Extensions.ImGui/PublicAPI/netstandard2.1/PublicAPI.Unshipped.txt
src/OpenGL/Extensions/Silk.NET.OpenGL.Legacy.Extensions.ImGui/Silk.NET.OpenGL.Legacy.Extensions.ImGui.csproj

Adds an OpenGL2.0 compatible ImGuiRenderer
I removed glVersion as it was never used and caused issues on older GL versions

Add Legacy OpenGL ImGuiController

---

README.md

`Android-aot` workload no longer exists, so it should be removed.
Added `maccatalyst`, since it is also included in `.github/workflows/deploy.yml` file. Not 100% sure if it is actually required.
Updated recommended Visual Studio 2019 to 2022, because 2019 does not officially support .NET6.

Update prerequisites in Readme

---

src/Windowing/Silk.NET.Windowing.Glfw/GlfwWindow.cs

On GLFW, it will error out if you set the OpenGL context profile on OpenGL versions less then 3.2
https://discord.com/channels/521092042781229087/587346162802229298/964611543406878780

Dont set context profile on OpenGL < 3.2

---

src/generators/Silk.NET.SilkTouch.Emitter/CSharpEmitter.cs
tests/Silk.NET.SilkTouch.Emitter.Tests/IdentifierTests.cs

Note that tests are indeed failing, but this is due to an oddity in roslyn that means Identifiers are created with trivia. Investigating but I'd like to merge this, ignoring the failing tests. I think it's worth tracking this oddity, but not worth blocking on.

Better Identifier Emission & State Handling

---

documentation/for-contributors/generators/emitter/visitor.md

(sorry forgot the branch prefix)

Basic Emitter/Visitor docs

---

src/Windowing/Silk.NET.Windowing.Glfw/GlfwWindow.cs

When using the default GLFW backend, setting the window option `IsVisible` to `true` will be without effect. It seems, that this is due to the logic in `GlfwWindow.GCoreInitialize` that sets the core window state after hiding the window. This leads to calls such as `Glfw.RestoreWindow` which subsequently unhides the window again.
This PR naively prevents `GlfwWindow.CoreWindowState` from being set when the window should be hidden which leads to the desired outcome.
* Check out Silk.net on the main branch. Tested with 4dd24efed9eeb416268d9634ed5a3bb9ddf58ff9
* Open Silk.net.sln and set the ImGui project as startup project
* Replace the line 
`            using var window = Window.Create(WindowOptions.Default);`
with
```
var wndOptions = WindowOptions.Default;
wndOptions.IsVisible = false; …
```

GLFW windows cannot be created as invisible

---

src/Windowing/Silk.NET.Windowing.Sdl/SdlView.cs

When using the SDL backend with more than one window, clicking the main window's close button will be ignored. This does not happen when using the GLFW backend.
As discussed e.g. at https://stackoverflow.com/questions/17541127/sdl-2-0-quit-event-with-multiple-windows, SDL emits a dedicated window-close event that's not currently handled. This PR adds a suitable event handling so users can now close the SDL window.
* Check out Silk.net on the main branch. Tested with 4dd24efed9eeb416268d9634ed5a3bb9ddf58ff9
* Open Silk.net.sln and set the ImGui project as startup project
* Add a 2nd window by replacing the lines
```
// Now that everything's defined, let's run this bad boy!
window.Run();
```
with
```
window.Initialize();
using var window2 = Window.Create(WindowOptions.Default); …
```

Closing an SDL window fails when multiple window were created

---

examples/CSharp/OpenGL Tutorials/Tutorial 3.5 - Lighting Maps/Program.cs

"diffuse" changed to "specular" in a comment about binding the specular map

Fixed a mistake in a comment

---

src/Core/Silk.NET.Core/Loader/DefaultPathResolver.cs

Currently if some resolver produce exception it fails whole resolution process. When code runs in the unanticipated configurations. Like NativeAOT without reflection, even if one resolver does not make sense to that environment, others can find native dependencies just fine. So that's unlock unforeseen environments.
Related #960

Do not fail resolution process on resolver failure

---

src/generators/Silk.NET.SilkTouch.Emitter/CSharpEmitter.cs
src/generators/Silk.NET.SilkTouch.Scraper/XmlVisitor.cs
src/generators/Silk.NET.SilkTouch.Symbols/ExternalTypeReference.cs
src/generators/Silk.NET.SilkTouch.Symbols/FieldSymbol.cs
src/generators/Silk.NET.SilkTouch.Symbols/IdentifierSymbol.cs
src/generators/Silk.NET.SilkTouch.Symbols/SymbolVisitor.cs
tests/Silk.NET.SilkTouch.Emitter.Tests/EmitterFieldTests.cs
tests/Silk.NET.SilkTouch.Emitter.Tests/EmitterStructMemberFieldsTests.cs
tests/Silk.NET.SilkTouch.Scraper.Tests/FieldScrapingTests.cs
tests/Silk.NET.SilkTouch.Symbols.Tests/ExternalTypeReferenceTests.cs
tests/Silk.NET.SilkTouch.Symbols.Tests/SymbolVisitorTests/ExternalTypeReferenceTests.cs
tests/Silk.NET.SilkTouch.Symbols.Tests/SymbolVisitorTests/FieldTests.cs
tests/Silk.NET.SilkTouch.Symbols.Tests/SymbolVisitorTests/StructTests.cs

This replaces the awkward type symbol used by fields with a new symbol "ExternalTypeReference"
This also lays the foundation for typing methods correctly

External Type Reference

---

documentation/for-contributors/generators/emitter/about formatting.md
src/generators/Silk.NET.SilkTouch.Emitter/CSharpEmitter.cs
tests/Silk.NET.SilkTouch.Emitter.Tests/EmitterNamespaceMemberTests.cs
tests/Silk.NET.SilkTouch.Emitter.Tests/EmitterNamespaceTests.cs
tests/Silk.NET.SilkTouch.Emitter.Tests/EmitterStructMemberFieldsTests.cs
tests/Silk.NET.SilkTouch.Emitter.Tests/EmitterStructTests.cs
tests/Silk.NET.SilkTouch.IntegrationTests/StructIntegrationTests.Test1.verified.txt
tests/Silk.NET.SilkTouch.IntegrationTests/StructIntegrationTests.Test2.verified.txt
tests/Silk.NET.SilkTouch.IntegrationTests/StructIntegrationTests.Test4.verified.txt

Example from Integration1:
```diff
@@ -4,9 +4,9 @@
namespace LIBRARY_NAMESPACE
{
-public struct Test
-{
-    public int f1;
-    public int f2;
-}
+    public struct Test
+    {
+        public int f1;
+        public int f2;
+    }
}
```

Introduce new Formatting & Adjust tests

---

.nuke/build.schema.json
src/Windowing/Silk.NET.Windowing.Common/PublicAPI/netstandard2.0/PublicAPI.Unshipped.txt
src/Windowing/Silk.NET.Windowing.Common/PublicAPI/netstandard2.1/PublicAPI.Unshipped.txt
src/Windowing/Silk.NET.Windowing.Common/Structs/VideoMode.cs

Adds a built-in aspect ratio calculation for the `VideoMode`.
A user can query a video mode's aspect ratio and it will return a `Vector2D<int>` with the calculated aspect ratio (although will be precalculated for speed).
[Small discussion, confirming I am creating a PR.](https://discordapp.com/channels/521092042781229087/521092043288608781/1003327705036624003)
None.

Aspect ratio calculation for VideoModes

---

examples/CSharp/OpenGL Tutorials/Tutorial 1.4 - Textures/Texture.cs
examples/CSharp/OpenGL Tutorials/Tutorial 1.5 - Transformations/Texture.cs
examples/CSharp/OpenGL Tutorials/Tutorial 2.1 - Co-ordinate Systems/Texture.cs
examples/CSharp/OpenGL Tutorials/Tutorial 2.2 - Camera/Texture.cs
examples/CSharp/OpenGL Tutorials/Tutorial 3.5 - Lighting Maps/Texture.cs

This PR adds texture completeness for mipmaps. By default its something like min 0 to max 1000 levels. They were also never used by the minification filter.
* https://discord.com/channels/521092042781229087/607634593201520651/997288821764923514
See https://www.khronos.org/opengl/wiki/Texture#Texture_completeness

Texture completeness for examples

---

src/Core/Silk.NET.Core/Loader/DefaultPathResolver.cs

Before it would append the dll name onto the folder it was supposed to check, meaning when it looked for the file itd be /runtimes/arch/native/dll/dll.so rather than /runtimes/arch/native/dll.so
https://canary.discord.com/channels/521092042781229087/1004485065838956604/1004486394514776126

Fix runtime folder path checking

---

documentation/proposals/Proposal - Windowing 3.0.md

This changes the "SurfaceExtensions" proposal's "SetDefaultIcon" method to correctly use IDesktopSurface, and not the nonexistent IDesktopWindow interface.
This is just a minor typo fix, nothing major

Fixing minor typo

---

Directory.Packages.props
src/generators/Silk.NET.SilkTouch.Scraper/ClangScraper.cs
src/generators/Silk.NET.SilkTouch.Scraper/XmlVisitor.cs
tests/Silk.NET.SilkTouch.IntegrationTests/Silk.NET.SilkTouch.IntegrationTests.csproj
tests/Silk.NET.SilkTouch.IntegrationTests/StructIntegrationTests.cs
tests/Silk.NET.SilkTouch.IntegrationTests/TestHelper.cs
tests/Silk.NET.SilkTouch.Scraper.Tests/BasicXMLTests.cs
tests/Silk.NET.SilkTouch.Scraper.Tests/FieldScrapingTests.cs
tests/Silk.NET.SilkTouch.Scraper.Tests/Helpers.cs
tests/Silk.NET.SilkTouch.Scraper.Tests/IdentityScrapingTests.cs
tests/Silk.NET.SilkTouch.Scraper.Tests/NamespaceScrapingTests.cs
tests/Silk.NET.SilkTouch.Scraper.Tests/Silk.NET.SilkTouch.Scraper.Tests.csproj
tests/Silk.NET.SilkTouch.Scraper.Tests/StructMemberScrapingTests.cs
tests/Silk.NET.SilkTouch.Scraper.Tests/StructScrapingTests.cs

This visits types correctly.
Tests will fail, which is an unfortunate necessity to not make commits too large.

Correctly Visit types

---

.github/workflows/test.yml
Directory.Packages.props
src/generators/Silk.NET.SilkTouch.Scraper/ClangScraper.cs
src/generators/Silk.NET.SilkTouch.Scraper/ClangScraperConfiguration.cs
tests/Silk.NET.SilkTouch.IntegrationTests/Silk.NET.SilkTouch.IntegrationTests.csproj
tests/Silk.NET.SilkTouch.IntegrationTests/StructIntegrationTests.cs
tests/Silk.NET.SilkTouch.IntegrationTests/TestHelper.cs
tests/Silk.NET.SilkTouch.Scraper.Tests/BasicXMLTests.cs
tests/Silk.NET.SilkTouch.Scraper.Tests/Helpers.cs
tests/Silk.NET.SilkTouch.Scraper.Tests/Silk.NET.SilkTouch.Scraper.Tests.csproj

Enables OSX Support & Resolves default Includes

Default includes

---

src/generators/Silk.NET.SilkTouch.Scraper/XmlVisitor.cs
src/generators/Silk.NET.SilkTouch.Symbols/SymbolVisitor.cs
src/generators/Silk.NET.SilkTouch.Symbols/UnresolvedTypeReference.cs
tests/Silk.NET.SilkTouch.IntegrationTests/StructIntegrationTests.cs
tests/Silk.NET.SilkTouch.Scraper.Tests/FieldScrapingTests.cs
tests/Silk.NET.SilkTouch.Symbols.Tests/SymbolVisitorTests/UnresolvedTypeReferenceTests.cs

Groundwork for multi-pass type resolution

Unresolved type symbol

---

src/Microsoft/Silk.NET.XInput/XInput.cs

Adds an implementation of `GetApi()` for XInput which currently throws a not implemented exception.
https://discord.com/channels/521092042781229087/587346162802229298/1007383458978467920
None.

Fix xinput GetApi()

---

src/Windowing/Silk.NET.Windowing.Glfw/GlfwWindow.cs

This fixes a bug when setting TransparentBuffer to true and leaving PreferredBitDepth null, the transparent buffer would not be applied correctly.
You can do this to "hotfix" the problem until this is merged:
`options.PreferredBitDepth      = new Vector4D<int>(8);`

Fixing TransparentBuffer when AlphaBits is not set by the user

---

src/OpenAL/Extensions/Silk.NET.OpenAL.Extensions.EXT/Disconnect.cs
src/OpenAL/Extensions/Silk.NET.OpenAL.Extensions.EXT/Enums/DisconnectContextInteger.cs
src/OpenAL/Silk.NET.OpenAL.Tests/ExtensionLoadingTests.cs

This adds support for the Disconnect extension for OpenAL (ALC_EXT_disconnect).
Reference: http://icculus.org/alextreg/wiki/action=printer&id=ALC_EXT_Disconnect
This extension provides much needed functionality to OpenAL for detecting whether audio devices have been disconnected. This can happen for USB headsets, etc, and it is often necessary for applications to switch to a different device when this happens.

Add support for OpenAL disconnect extension

---

src/Core/Silk.NET.Core/Loader/DefaultPathResolver.cs
src/Windowing/Silk.NET.Windowing.Common/Window.cs

This class is unsupported when using WASM/WASI-SDK
[Links go here.](https://discord.com/channels/521092042781229087/521092043288608781/1030598895497121833)

try/catch usages of System.Diagnostics.Process

---

src/Lab/Experiments/PrototypeStructChaining/PrototypeStructChaining.Test/PrototypeStructChaining.Test.csproj
src/OpenAL/Silk.NET.OpenAL.Tests/Silk.NET.OpenAL.Tests.csproj
src/Vulkan/Silk.NET.Vulkan.Tests/Silk.NET.Vulkan.Tests.csproj

This seems to be causing a CI failure, so lets revert

Revert "Bump coverlet.collector from 3.1.2 to 3.2.0 (#1126)"

---

examples/CSharp/OpenAL Demos/WavePlayer/Program.cs

Usually wav-files have their data section at 44 bytes, but not always. This fix removes a loud pop at the start of playback on those rare cases.

Fix incorrect slice start index in OpenAL exsample

---

src/Core/Silk.NET.BuildTools/Program.cs

Makes BuildTools classes/methods public to allow external consumption through NuGet
[Links go here.](https://discord.com/channels/521092042781229087/587346162802229298/1041041517780934736)

Make BuildTools related classes/methods public

---

src/OpenAL/Extensions/Silk.NET.OpenAL.Extensions.EXT/FloatFormat.cs

Currently you have to explicitly cast FloatBufferFormat to BufferFormat to use the AL::BufferFormat function. alBufferFormat takes in two new enums provided by AL_EXT_float32  to provide the ability to load floating point data into openal buffer objects.
Issue Ref: #1149
[Spec Ref](https://github.com/openalext/openalext/blob/master/AL_EXT_float32.txt)
There may be a possibility that the Capture feature of OpenAL supports floating point audio. I have no mind to include this because it adds more research that isn't easily presented in google. Silk.NET doesn't compile too well either. So, to keep it simple I won't add anything to do with anything other than what the spec AL_EXT_float32 says.

Implement extensions functions to make use of AL_EXT_float32 enums

---

src/Core/Silk.NET.Core/Contexts/INativeWindow.cs
src/Core/Silk.NET.Core/Contexts/NativeWindowFlags.cs
src/Windowing/Silk.NET.GLFW/GlfwNativeWindow.cs
src/Windowing/Silk.NET.SDL/SdlNativeWindow.cs

Adds EGL display and surface to INativeWindow
https://discord.com/channels/521092042781229087/521092043288608781/1051400061608788009
This is required to use cl_khr_gl_sharing on platforms like Wayland which use EGL for GL contexts

Add EGL display and surface to INativeWindow

---

src/OpenGL/Extensions/Silk.NET.OpenGL.Extensions.ImGui/Silk.NET.OpenGL.Extensions.ImGui.csproj

Updates ImGui.NET to latest version
Latest version of ImGui.NET fixes the issue of using it on Apple silicon devices (M1/M2).

Update ImGui.NET to latest

---

src/Microsoft/Silk.NET.DXGI/NativeWindowExtensions.cs

Uses DXHandle instead of windows HWND
Discussed in the working group meeting
related tracker: https://github.com/orgs/dotnet/projects/64/views/13?pane=issue&itemId=17581240

Use DXHandle for creating DXGI swapchain

---

src/Lab/Experiments/ImGuiVulkan/ImGuiVulkan.csproj
src/Lab/Experiments/ImGuiVulkan/ImGuiVulkanApplication.cs
src/Vulkan/Silk.NET.Vulkan/VulkanLibraryNameContainer.cs

The current implementation only works on Windows, based on my tests it was never validated over MoltenVK,
I successfully managed to run on the Mac after troubleshooting and fixing the Vulkan initialisation config.
My proposal is to bring the fixes to the Experiment and hopefully some enhancements to make this an official example.

Fix to ImGuiVulkan Experiment to run on MacOSX

---

src/OpenAL/Extensions/Silk.NET.OpenAL.Extensions.Soft/ReopenDevices.cs

Adds `ReopenDevices` extension for OpenAL soft.
OpenAL Soft Documentation: https://openal-soft.org/openal-extensions/SOFT_reopen_device.txt

Add ReopenDevices extension for OpenAL Soft

---

.github/workflows/build.yml
build/props/common.props
global.json

This allows for more rapid iteration times and assurance against timeouts in release pipelines (which has been a big problem!)
- use windows-quick (self-hosted only) for release tags on this repo
- use windows-2022 (self-hosted or GitHub-hosted depending on what's available) for development in this repo
- use windows-latest (GitHub-hosted only) in all other cases (i.e. community contributions)
Note: the reason we use windows-2022 instead of windows-latest is so that both the self-hosted runner
(which has the windows-2022 label but NOT the windows-latest label) and the GitHub hosted runner are
treated as candidates. We will never have a windows-latest self-hosted runner even if it is the latest. 
There is currently only one self-hosted runner (`useaz1-githubrunner1v` aka US East Azure 1 …

Use a self-hosted runner

---

src/Vulkan/VMASharp_API_For_Review.md

Makes usage closer to the rest of the Vulkan bindings/Silk.NET APIs as a whole, as we tend to prefer nint over `IntPtr`

Move VMASharp proposed API over to nint

---

src/OpenAL/Extensions/Silk.NET.OpenAL.Extensions.Soft/Enums/SoftBufferCallback.cs
src/OpenAL/Extensions/Silk.NET.OpenAL.Extensions.Soft/SoftCallbackBuffer.cs
src/OpenAL/Extensions/Silk.NET.OpenAL.Extensions.Soft/Structs/PfnBufferCallback.cs

Implements the openal-soft extension AL_SOFT_callback_buffer
It seems checking whether OpenAL extensions are available is broken, but that looks like an unrelated problem to solve at a later time

Implement AL_SOFT_callback_buffer extension

---

src/Windowing/Silk.NET.GLFW/Enums/AnglePlatformType.cs
src/Windowing/Silk.NET.GLFW/Enums/Bool.cs
src/Windowing/Silk.NET.GLFW/Enums/InitHint.cs
src/Windowing/Silk.NET.GLFW/Glfw.cs

+ Add Bool Enum (for GLFW_TRUE/GLFW_FALSE)
+ Add AnglePlatformType Enum for InitHint (added in GLFW 3.4)
+ Change InitHint to use int, as the official glfw library.
Issue #1317 
Thanks guys.

Adding ANGLE: Changes via conversation in issue #1317

---

src/Vulkan/Silk.NET.Vulkan/VulkanLibraryNameContainer.cs

https://github.com/dotnet/Silk.NET/pull/1197#discussion_r1168295230
MoltenVK is (obviously) above portability, and while gfx-rs/portability is dead development wise, there are maybe people who want to package it with their app and use it for whatever reason, or end users who want to use it with some app, so lets shove it at the end of the libnames to check, since we are able to, and it shouldnt hurt anything, given the loader and Molten VK are prioritized

Vulkan: Add MoltenVK and portability to MacOS library names

---

src/Vulkan/Silk.NET.Vulkan/Chain.g.cs
src/Vulkan/Silk.NET.Vulkan/Chain.g.tt

Adds HeadRef and ItemNRef to the managed Chain types in Silk.NET.Vulkan to support easier modification of properties on chain elements, as well as pulling the setters up to the interfaces.

Further chain improvements

---

.github/workflows/build.yml
src/Website/Silk.NET.Statiq/Program.cs
website/docs/silk.net/experimental-feed.md
website/docs/silk.net/index.md
website/nuget/experimental/index.json

The experimental builds are now hosted on GitLab herein. This is because it has a 250GB limit instead of the "2GB" one we have with Azure Artifacts (though we were using ~7.5GB somehow?)
The feed URL is https://dotnet.github.io/Silk.NET/nuget/experimental/index.json - this is https://gitlab.com/api/v4/projects/47661606/packages/nuget/index.json but mirrored to our site so we can give a URL to our users that we have control over, meaning future switches between experimental feed hosts are seamless.
This also adds back the documentation page on the experimental feed that was never ported over from docs.ultz.co.uk

New experimental feed

---

src/Maths/Silk.NET.Maths/PublicAPI/net5.0/PublicAPI.Shipped.txt
src/Maths/Silk.NET.Maths/PublicAPI/net6.0-android/PublicAPI.Shipped.txt
src/Maths/Silk.NET.Maths/PublicAPI/net6.0-ios/PublicAPI.Shipped.txt
src/Maths/Silk.NET.Maths/PublicAPI/netcoreapp3.1/PublicAPI.Shipped.txt
src/Maths/Silk.NET.Maths/PublicAPI/netstandard2.0/PublicAPI.Shipped.txt
src/Maths/Silk.NET.Maths/PublicAPI/netstandard2.1/PublicAPI.Shipped.txt
src/Maths/Silk.NET.Maths/SystemNumericsExtensions.cs

I noticed that Vector4D<T> doesn't has the ToSystem function and Vector4 doesn't has the ToGeneric function, these functions in SystemNumericsExtensions class doesn't has the `this` keyword, so... I'll try to fix it. It's my first contributing experience so I'm sorry if I will make mistakes

Fix missing "this" keyword in ToSystem and ToGeneric for 4d vector

---

src/Core/Silk.NET.Core/Miscellaneous/Bool32.cs

I noticed that Bool32 doesn't have any `==` or `!=` operators and thought it would be nice to add them. @Perksey hinted at PRs for this in #1586, so here it is!
This adds equality operators for comparing `Bool32` with `Bool32`, `bool` or `uint`
This is my first Silk.NET PR, so feel free to tell me if I've missed something.
Closes #1586

Equality operators for Bool32

---

src/Core/Silk.NET.Core/Miscellaneous/Bool32.cs

This is a follow-up to a suggestion by @Khitiara in PR #1587, to implement `IEquatable<Bool32>`, `IEquatable<bool>` and `IEquatable<uint>` in `Bool32`.
As always, let me know if I missed anything. :)

Implement IEquatable in Bool32

---

src/Core/Silk.NET.Core/Miscellaneous/BreakneckSleep.cs
src/Lab/Experiments/TimeTrials/Program.cs

Fixes BreakneckSleep in the existing CPU usage PR to store the last tick timestamp and compare to that instead of to when Sleep is called.
The branch still doesnt actually use BreakneckSleep in the window loop but still this is in theory an improvement

Proper frame timing in BreakneckSleep

---

src/OpenAL/Extensions/Silk.NET.OpenAL.Extensions.EXT/Enums/MCBufferFormat.cs
src/OpenAL/Extensions/Silk.NET.OpenAL.Extensions.EXT/MCFormats.cs

This PR adds support for the `AL_EXT_MCFORMATS` extension.
Help was asked for here: <https://discordapp.com/channels/521092042781229087/727266595826696303/1142111300336500766>. It seemed like finally something I could do and understand, so here we are. 
_none_

OpenAL MCFormats extension

---

src/Lab/Experiments/ImGuiVulkan/ImGuiVulkan.csproj
src/OpenGL/Extensions/Silk.NET.OpenGL.Extensions.ImGui/Silk.NET.OpenGL.Extensions.ImGui.csproj
src/OpenGL/Extensions/Silk.NET.OpenGL.Legacy.Extensions.ImGui/Silk.NET.OpenGL.Legacy.Extensions.ImGui.csproj
src/OpenGL/Extensions/Silk.NET.OpenGLES.Extensions.ImGui/Silk.NET.OpenGLES.Extensions.ImGui.csproj

Updates ImGui.NET from 1.88.0 to 1.89.7.1 (latest)
N/A
The latest versions of ImGui.NET allow users to pass `ReadOnlySpan<char>` instead of `string` on platforms where `ReadOnlySpan` is supported, saving GC overhead in UI render loops.
The main reason why I'd like to use this is so I can write allocation-free UI code so actual memory allocations happening in my engine are easier to spot. 🙂
I'm also curious if it would be possible to get a pre-release version released for `Silk.NET.OpenGL.Extensions.ImGui`. If that's normally not done, that's fine. I don't mind waiting for the next release.
Please let me know if I've missed anything.

Update ImGui.NET from 1.88.0 to 1.89.7.1

---

build/nuke/Native/Core.cs

Adds a glob for MoltenVK binaries built during CI runs. This fixes the issue of CI workflows excluding built binaries from commits.
No related issues.

Add CI commit glob for MoltenVK binaries

---

src/OpenAL/Extensions/Silk.NET.OpenAL.Extensions.Soft/Enums/SoftEffectSlotInteger.cs
src/OpenAL/Extensions/Silk.NET.OpenAL.Extensions.Soft/SoftEffectTarget.cs
src/OpenAL/Silk.NET.OpenAL.Tests/ExtensionLoadingTests.cs

This change adds support for the OpenAL Soft EffectTarget extension, which allows effects to be chained.

Add support for OpenAL EffectTarget extension

---

src/Lab/Experiments/ImGuiVulkan/ImGuiVulkan.csproj
src/Lab/Experiments/ImGuiVulkan/Lib/ImGuiController.cs
src/OpenGL/Extensions/Silk.NET.OpenGL.Extensions.ImGui/ImGuiController.cs
src/OpenGL/Extensions/Silk.NET.OpenGL.Extensions.ImGui/Silk.NET.OpenGL.Extensions.ImGui.csproj
src/OpenGL/Extensions/Silk.NET.OpenGL.Legacy.Extensions.ImGui/Silk.NET.OpenGL.Legacy.Extensions.ImGui.csproj
src/OpenGL/Extensions/Silk.NET.OpenGLES.Extensions.ImGui/Silk.NET.OpenGLES.Extensions.ImGui.csproj

Updates ImGui.NET from 1.89.7.1 to 1.89.9.3. This fixes `System.MissingMethodException` occurring whenever an ImGui method with a non-ref string parameter is called. The following fix is included in the new ImGui.NET version: https://github.com/ImGuiNET/ImGui.NET/pull/439
The [Silk.NET ImGui sample](https://github.com/dotnet/Silk.NET/tree/main/examples/CSharp/OpenGL%20Demos/ImGui) currently fails on main, but works correctly on this branch. I've also tested some of my own projects. Everything runs correctly on both .NET Standard 2.0 and .NET 7.0. (I have not explicitly tested .NET 6.0 but I do not expect any issues there.)
https://github.com/ImGuiNET/ImGui.NET/issues/436
https://github.com/dotnet/Silk.NET/issues/1757
The `CmdListsRange` -> `CmdLists` change is unrelated. `CmdListsRange` …

Update ImGui.NET from 1.89.7.1 to 1.89.9.3

---

src/OpenAL/Silk.NET.OpenAL.Tests/ExtensionLoadingTests.cs
src/OpenAL/Silk.NET.OpenAL/AL/AL.cs

This fixes the hack for calling `TryGetExtension` for the OpenAL EFX extension.
The `alcIsExtensionPresent` function call is missing a `Device*` argument. To be consistent with [`TryGetExtension` in ALContext](https://github.com/dotnet/Silk.NET/blob/521e18a36ca4d91393814a1b4ae6a9494a91fd9b/src/OpenAL/Silk.NET.OpenAL/ALC/ALContext.cs#L31C10-L31C10), we should pass in the current context's device.
[Issue](https://github.com/dotnet/Silk.NET/issues/1691)

Fix ALC_EXT_EFX hack

---

documentation/proposals/Proposal - 3.0 & 3.X Software Development Plan.md

Updates the proposal for the software development plan going forward such that preview/development builds are considered newer than the release they follow by standard semver/nuget conventions.
[![image](https://github.com/dotnet/Silk.NET/assets/3117019/939304ca-b1bd-4590-90dc-5a3a1ab9415b)](https://discord.com/channels/521092042781229087/587346162802229298/1157498331103236258)

Update proposed new versioning rules for easier preview build usage

---

src/OpenAL/Extensions/Silk.NET.OpenAL.Extensions.Soft/ReopenDevices.cs
src/OpenAL/Silk.NET.OpenAL.Tests/ExtensionLoadingTests.cs

Fixes the AL ReopenDevices extension to derive from `ContextExtensionBase` since it is a context extension.
[Issue](https://github.com/dotnet/Silk.NET/issues/1823)

Fix AL ReopenDevices extension

---

src/Core/Silk.NET.Core/Miscellaneous/BreakneckLock.cs

Fixes the implementation of BreakneckLock (only used in SDL2 event code).
Found this issue when trying to figure out why the SDL2 platform implementation had a low update rate for inputs. (first frame locking fails but actually acquires, second frame "succeeds" to acquire the already acquired lock)
Consider the following code: ([similar to platform impl](https://github.com/dotnet/Silk.NET/blob/e433e6f51d66b02118bc037251de5d4ade58e248/src/Windowing/Silk.NET.Windowing.Sdl/SdlPlatform.cs#L152))
```csharp
var l = new BreakneckLock();
var taken = false;
Console.Out.WriteLine($"IsAcquired before: {l.IsAcquired}");
l.TryEnter(ref taken);
Console.Out.WriteLine($"---- TryEnter ----");
Console.Out.WriteLine($"taken after: {taken}");
Console.Out.WriteLine($"IsAcquired after: {l.IsAcquired}");
taken …
```

Fix BreakneckLock

---

website/docs/silk.net/experimental-feed.md

The experimental feed docs should suggest using ``RestoreAdditionalProjectSources`` instead of ``RestoreSources``.  Overriding ``RestoreSources`` will make it so that packages will not be restored from nuget.org unless you explicitly add them to the list it like in the snippet below.
```xml
<RestoreSources>$(RestoreSources);nuget.org;https://dotnet.github.io/Silk.NET/nuget/experimental/index.json</RestoreSources>
```
The current example provided in the docs will always fail when adding new nuget packages since it only checks the gitlab registry for packages.
``No packages exist with this id in source(s): https://dotnet.github.io/Silk.NET/nuget/experimental/index.json``
I think ``RestoreAdditionalProjectSources`` should be used since it doesn't get rid of nuget.org as the default but still …

Update experimental feed docs to use RestoreAdditionalProjectSources

---

src/Input/Silk.NET.Input.Sdl/SdlInputContext.cs
src/Windowing/Silk.NET.Windowing.Common/Internals/ViewImplementationBase.cs
src/Windowing/Silk.NET.Windowing.Sdl/SdlView.cs
src/Windowing/Silk.NET.Windowing.Sdl/SdlWindow.cs

Currently the SDL windowing platform loses events when using multiple windows.
Flow of the bug:
- 1st Window DoEvents
- Previous events cleared
- Platform DoEvents
- SDL PollEvent
- Polled events dispatched to every window
- Events handled for this window
- 2nd Window DoEvents
- Previous events cleared **(and everything we just collected)**
- Platform DoEvents
- SDL PollEvent **(likely gives nothing since we just polled already)**
- Polled events dispatched to every window
- Events handled for this window **(there are none)**
The solution in this pr is to add a new (internal) AfterProcessingEvents method to (the internal) ViewImplementationBase, which performs the clearing of the event queue. Clearing at the end of DoEvents is too early for the input module.
I also took the liberty of …

Fix SDL2 platform losing events when using multiple windows/views

---

src/SPIRV/Silk.NET.SPIRV.Cross/Silk.NET.SPIRV.Cross.csproj
src/SPIRV/Silk.NET.SPIRV.Reflect/Silk.NET.SPIRV.Reflect.csproj
src/SPIRV/Silk.NET.Shaderc/Silk.NET.Shaderc.csproj

Reference native packages from managed SPIR-V packages.

---

.github/workflows/bindings-regeneration.yml
.github/workflows/build.yml
.github/workflows/public-api.yml
README.md
src/Lab/Experiments/TriangleNET6/TriangleNET6.csproj
src/Maths/Silk.NET.Maths/Silk.NET.Maths.csproj
src/Vulkan/Silk.NET.Vulkan/Silk.NET.Vulkan.csproj
src/Windowing/Silk.NET.Windowing.Sdl/Silk.NET.Windowing.Sdl.csproj
src/Windowing/Silk.NET.Windowing/Silk.NET.Windowing.csproj

Also update build instructions.
Closes #2014.

Make Silk.NET buildable on Linux by skipping iOS and Mac Catalyst stuff.

---

src/Windowing/Silk.NET.GLFW/GlfwNativeWindow.cs

Currently if wayland is used we say its X11 with no window or display ptr

GlfwNativeWindow: Allow wayland window ptr to be read when GLFW is compiled with both X11 and Wayland

---

src/Windowing/Silk.NET.Windowing.Common/Interfaces/IView.cs
src/Windowing/Silk.NET.Windowing.Common/Internals/ViewImplementationBase.cs
src/Windowing/Silk.NET.Windowing.Common/PublicAPI/netstandard2.0/PublicAPI.Shipped.txt
src/Windowing/Silk.NET.Windowing.Common/PublicAPI/netstandard2.1/PublicAPI.Shipped.txt
src/Windowing/Silk.NET.Windowing.Glfw/GlfwWindow.cs
src/Windowing/Silk.NET.Windowing.Sdl/SdlView.cs

Added SetFocus method to the Window
As was discussed here https://github.com/dotnet/Silk.NET/discussions/1526, both GLFW and SDL support this functionality and it is very usefull for the ImGui support, so it can be added to the window.
Unfortunately I wasn't be able to build the project, to check if everything is working correctly, could someone to pick it up? (I am asked for some reason to enter credentials for https://chrome-internal.googlesource.com that I don't have while recursive submodule update. Also I have tons of  errors on nuke compile like  Restore: \Silk.NET\src\Windowing\Silk.NET.Windowing.Sdl\S
ilk.NET.Windowing.Sdl.csproj : error NU1301: Failed to load service index for source https://gitlab.com/api/v4/projects/47661606/packages/nuget/index.js
on. …

Added SetFocus method to the Window

---

src/Input/Silk.NET.Input.Glfw/GlfwCursor.cs

This fixes unexpected behavior when setting the Standard Cursor using the GLFW backend as described at #2169.

Ensure that setting the GLFW mouse standard cursor works as expected

---

build/nuke/Native/SDL2.cs

This PR changes the SDL2 build to code-sign at the very end, fixing #2174. The build indicated:
> strip: warning: changes being made to the file will invalidate the code signature in: /Users/joskuijpers/Developer/Silk.NET/src/Native/Silk.NET.SDL.Native/runtimes/osx/native/libSDL2-2.0.dylib (for architecture x86_64)
strip: warning: changes being made to the file will invalidate the code signature in: /Users/joskuijpers/Developer/Silk.NET/src/Native/Silk.NET.SDL.Native/runtimes/osx/native/libSDL2-2.0.dylib (for architecture arm64)
On Mx systems, all binaries need a valid signature.
The build now adds a code sign, and has a new message: `libSDL2-2.0.dylib: replacing existing signature`

Add forced resigning of SDL2 outputs after stripping

---

website/_theme/src/11-navcontent.cshtml

The code responsible for making the github button used the incorrect variable, which resulted in the github button not leading to the proper URL.
Changed the code to use `githubLink` instead of `discordLink`.

Fix broken github link

---

src/OpenGL/Extensions/Silk.NET.OpenGL.Extensions.ImGui/ImGuiController.cs

The `ImGuiController::UpdateImGuiImput`  function creates a `MouseState` but never disposes it. 
This causes the `MemoryPool` to keep renting new buffers in the constructor, resulting in a small memory leak.

ImGui memory leak fix

---

.github/workflows/angle.yml
build/nuke/Native/Angle.cs

This PR adjusts the `Angle.cs` script to optimize disk space usage and also build fat binaries for MacOS (to work on both arm64 and x64 macs). For now, only MacOS builds are enabled.
Links go here.
https://github.com/dotnet/Silk.NET/issues/2024

Add CI builds (MacOS only) for ANGLE

---

src/Core/Silk.NET.Core/Contexts/INativeWindow.cs

Replaced "summaray" with "summary". This also makes the documentation tag parse correctly.

Fix typo in the spelling of "summary"

---

src/Windowing/Silk.NET.Windowing.Glfw/GlfwPlatform.cs
src/Windowing/Silk.NET.Windowing.Sdl/SdlPlatform.cs

Calling `GLFW.Glfw.GetApi();` when Glfw is applicable without disposing it leaks the native module. So we make sure `Dispose()` is called, which triggers freeing of the native library and reduce the 'counter'.
This was discovered when I was trying to delete the native library (`glfw3.dll`) on program exit. The delete failed because the program was still referencing the module.  
The codebase uses the lazy `GlfwProvider.GLFW` where it makes sense. When needed, the lazy implementation will have the `Dispose()` called, thus freeing `glfw3`. But because of the applicable check, the module will never truly be freed without calling `GlfwProvider.GLFW.Value._ctx.Dispose();` manually at least once after a Window creation

Dispose Glfw/Sdl When Checking if Applicable

---

src/Core/Silk.NET.Core/Miscellaneous/Bool32.cs

Creating a workaround for UWP native build based on issue reported some years ago in [this issue](https://github.com/microsoft/dotnet/issues/807) and similar pull request addressing this issue in https://github.com/SharpGenTools/SharpGenTools/pull/210
When building Blank UWP application with Silk.NET pulled from nuget on x64 release build, seeing the following error:
```
Error MCG0037: MCG0037:InvalidCSharpIdentifierName Struct 'Silk.NET.Core.Bool32' in assembly 'Assembly(Name=Silk.NET.Core, Version=2.22.0.0, Culture=neutral, PublicKeyToken=null, Location=<>\obj\x64\Release\ilc\in\Silk.NET.Core.dll)' has a field with name '<Value>k__BackingField' that is invalid. This could be because the name is obfuscated or the field is auto-implemented by the compiler. Please make sure the field name …
```

Workaround for UWP native build

---

src/Core/Silk.NET.Core/Silk.NET.Core.csproj
src/Lab/Experiments/PrototypeStructChaining/PrototypeStructChaining/PrototypeStructChaining.csproj

This is mainly to bump the transitive System.Text.Json dependency from 8.0.0 to 9.0.0, fixing https://github.com/advisories/GHSA-hh2w-p6rv-4g7w.
Closes #2370. As described in that issue, the System.Text.Json dependency is shipped to all consumers of the `Silk.NET.Core` package and will result in build warnings when building with the .NET 9 SDK.

Bump Microsoft.Extensions.DependencyModel

---

website/index.cshtml

Fixes the "remain" and "improvements" typos found on the website root of the github.io pages.
Untested

Fix typos on the website root page

---

src/Windowing/Silk.NET.Windowing.Sdl/Silk.NET.Windowing.Sdl.csproj

Android applications currently can't build due to type duplication issues. It turns out we've been shipping the same AAR twice and haven't noticed until now.

Fix aar duplication for Android

---

src/OpenAL/Extensions/Silk.NET.OpenAL.Extensions.Creative/EnumerateAll.cs
src/OpenAL/Extensions/Silk.NET.OpenAL.Extensions.EXT/CaptureEnumerationEnumeration.cs
src/OpenAL/Extensions/Silk.NET.OpenAL.Extensions.Enumeration/Enumeration.cs

`Marshal.PtrToStringAnsi` uses the system codepage which is problematic especially on windows. OpenAL returns UTF-8 strings which should be parsed as UTF-8.
Using the following test code:
```csharp
var api = ALContext.GetApi();
api.TryGetExtension<EnumerateAll>(null, out var enumerateAll);
var deviceEnumerable = enumerateAll.GetStringList(GetEnumerateAllContextStringList.AllDevicesSpecifier);
foreach (var deviceName in deviceEnumerable)
{
Console.WriteLine(deviceName);
}
```
with a non-utf-8 codepage and a device named `test ドットネット`, I get:
before:
`OpenAL Soft on test ãƒ%ãƒƒãƒ^ãƒ?ãƒƒãƒ^ (Realtek High Definition Audio)`
after (with proper console encoding configured):
`OpenAL Soft on test ドットネット (Realtek High Definition Audio)`

Use UTF-8 for OpenAL string marshalling

---

src/Assimp/Silk.NET.Assimp/Enums/PostProcessSteps.cs

This very simple PR merely adds the missing GenerateBoundingBoxes flag to Assimp that allows generating a mesh's Axis Aligned Bounding Box (AABB) on import, which is important in several use cases such as game engines to figure out the size of a mesh for collision or culling purposes.
The flag's value can be found at https://github.com/assimp/assimp/blob/master/include/assimp/postprocess.h#L605
I believe this is an important flag to keep, and I'd love to have your feedback if you have any!

[Assimp] Add missing GenerateBoundingBoxes flag

---

src/OpenGL/Extensions/Silk.NET.OpenGL.Extensions.ImGui/ImGuiController.cs

Changes `ImGuiController.TranslateInputKeyToImGuiKey` to no longer throw a `NotImplementedException` when given an unknown key and instead gracefully map to `ImGuiKey.None`, the ImGui equivalent of an unmapped/discarded key.
Fixes #2372.

Gracefully map unknown or invalid `Input.Key` to `ImGuiKey.None`.
