dotnet/Silk.NET

azure-pipelines.yml

Attempt to fix Azure pipelines

---

documentation/proposals/Proposal - Rumble.md

- Adds vibration to gamepads
- Supports multiple vibration motors, e.g for HD Rumble.
#38

A proposal for a vibration/rumble API.

---

README.md

Fix the link to fred's github page

---

documentation/proposals/Proposal - Windowing (Revision).md

Adds a proposal for expanding the windowing API.

Revise the windowing API to allow for more freedom

---

src/OpenAL/Extensions/Silk.NET.OpenAL.Extensions.Creative/XRam.cs
src/OpenAL/Extensions/Silk.NET.OpenAL.Extensions.Soft/DeferredUpdates.cs
src/OpenAL/Extensions/Silk.NET.OpenAL.Extensions.Soft/Soft.cs
src/OpenAL/Silk.NET.OpenAL/AL/AL.cs
src/OpenAL/Silk.NET.OpenAL/AL/Interfaces/IALExtension.cs
src/OpenAL/Silk.NET.OpenAL/ALC/ALContext.cs

Fix AL/ALC TypeLoadException

---

src/Input/Silk.NET.Input.Common/Enums/ButtonName.cs
src/Input/Silk.NET.Input.Desktop/GlfwInputContext.cs

Synchronises the indicies of ButtonName with that of GLFW.
#67 (not fixed)

[WIP] Fix gamepad mapping issues

---

src/Input/Silk.NET.Input.Common/GamepadExtensions.cs

dOES wHAT iT sAYS oN tHE tIN
Closes #69 (nice)

Add extensions for fetching buttons on gamepads

---

examples/F#/OpenGL/Tutorial 1.2 - Hello Triangle/Program.fs

Created this here as don't have access to Fred's repo yet and he doesn't have the latest code from upstream. Will commit future PRs to his repo.

Fsharp tutorial 1.2 matchup tweaks with C# tuts

---

src/Input/Silk.NET.Input.Common/Enums/CursorMode.cs
src/Input/Silk.NET.Input.Common/Enums/CursorType.cs
src/Input/Silk.NET.Input.Common/Enums/StandardCursor.cs
src/Input/Silk.NET.Input.Common/Interfaces/ICursor.cs
src/Input/Silk.NET.Input.Common/Interfaces/IMouse.cs
src/Input/Silk.NET.Input.Desktop/GlfwCursor.cs
src/Input/Silk.NET.Input.Desktop/GlfwMouse.cs

This adds the implementation of the cursor interface. Aside custom cursors there is now also the option to use standard (built-in) cursor shapes.

Added cursor types and implemented whole cursor logic

---

build/binder_specifications/OpenCL.json
build/binder_specifications/Vulkan.json
src/Core/BuildTools/Bind/Overloading/Overloader.cs
src/Core/BuildTools/Bind/Overloading/PointerParameterOverloader.cs
src/Core/BuildTools/Bind/Overloading/SpanOverloader.cs
src/Core/BuildTools/Common/Functions/Count.cs
src/Core/BuildTools/Common/Functions/Type.cs
src/Lab/VulkanTriangle/HelloTriangleApplication.cs
src/OpenGL/Silk.NET.OpenGL.Legacy/GL.cs
src/OpenGL/Silk.NET.OpenGL/GL.cs
src/OpenGL/Silk.NET.OpenGLES/GL.cs
src/Vulkan/Silk.NET.Vulkan/Vk.cs

Add some improvements to the overloaders.
Links go here.

Alter overloads

---

src/Input/Silk.NET.Input.Common/Interfaces/ICursor.cs
src/Input/Silk.NET.Input.Desktop/GlfwCursor.cs
src/Windowing/Silk.NET.GLFW/Enums/CursorStateAttribute.cs
src/Windowing/Silk.NET.GLFW/Glfw.cs

Extend ICursor interface to make cursor mode changeable. Implement cursor mode behavior for GLFWCursor.
Fixes #124

Implement cursor modes

---

README.md

Update README.md to reflect latest administrative changes

---

src/Windowing/Silk.NET.Windowing.Common/WindowExtensions.cs

Update default game loop

---

src/Windowing/Extensions/Silk.NET.Windowing.Extensions/WindowManager.cs
src/Windowing/Silk.NET.Windowing.Common/Interfaces/IView.cs
src/Windowing/Silk.NET.Windowing.Common/Interfaces/IWindowPlatform.cs
src/Windowing/Silk.NET.Windowing.Desktop/GlfwPlatform.cs
src/Windowing/Silk.NET.Windowing.Desktop/GlfwWindow.cs
src/Windowing/Silk.NET.Windowing/Window.cs

Add IsCurrent and ClearCurrent

---

src/Input/Silk.NET.Input.Common/Interfaces/IMouse.cs
src/Input/Silk.NET.Input.Desktop/GlfwInputContext.cs
src/Input/Silk.NET.Input.Desktop/GlfwMouse.cs
src/Lab/InputTest/Program.cs

Add events for single click and double click.
Closes #78

Add click events

---

build/binder_bakery_info/Vulkan.json
build/binder_scripts/fullrun.json
build/binder_specifications/EGL.json
build/binder_specifications/OpenCL.json
src/Core/BuildTools/Baking/FunctionDocumentation.cs
src/Core/BuildTools/Baking/ParameterDocumentation.cs
src/Core/BuildTools/Bind/ProfileWriter.cs
src/Core/BuildTools/Common/Structs/Field.cs
src/Core/BuildTools/Converters/Khronos/EnumDefinition.cs
src/Core/BuildTools/Converters/Khronos/FeatureDefinition.cs
src/Core/BuildTools/Converters/Khronos/StructureDefinition.cs
src/Core/BuildTools/Converters/Khronos/VulkanSpecification.cs
src/Core/BuildTools/Converters/Readers/VulkanReader.cs
src/Core/Silk.NET.Core/Native/NativeAPI.cs
src/Vulkan/Silk.NET.Vulkan/Structs/Bool32.cs
src/Vulkan/Silk.NET.Vulkan/Structs/Version32.cs
src/Vulkan/Silk.NET.Vulkan/Vk.cs

- Update to Vulkan 1.2
- Fix a bug where alias structs didn’t have any fields.
- Added struct constructors which also set the structure type to an appropriate value by default.
- Fix a bug where promoted extension enumerants were not present.
- Add version helper struct
- Improved boolean handling with a boolean helper struct
Links go here.

Vulkan improvements

---

azure-pipelines.yml

When we push a tag, a build will be pushed to NuGet.
Links go here.

Update build pipeline

---

src/Windowing/Silk.NET.Windowing.Common/Interfaces/IWindowProperties.cs
src/Windowing/Silk.NET.Windowing.Common/WindowOptions.cs
src/Windowing/Silk.NET.Windowing.Desktop/GlfwWindow.cs

Adds the ability to create a window with a transparent framebuffer.
Closes #151 
None.

Transparent framebuffers

---

Silk.NET.sln.DotSettings
src/Windowing/Silk.NET.Windowing.Common/Interfaces/IView.cs
src/Windowing/Silk.NET.Windowing.Common/WindowOptions.cs
src/Windowing/Silk.NET.Windowing.Desktop/GlfwWindow.cs

Add IDispose to IView and all deriving classes.
Closes #150

Implement IDispose on IView

---

src/OpenAL/Silk.NET.OpenAL/AL/AL.cs

OpenAL fixes

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/everything-else.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/pull_request_template.md

Update GitHub templates

---

src/OpenAL/Extensions/Silk.NET.OpenAL.Extensions.Creative/EffectExtension.cs
src/OpenAL/Extensions/Silk.NET.OpenAL.Extensions.Creative/EffectExtensionContext.cs
src/OpenAL/Extensions/Silk.NET.OpenAL.Extensions.Creative/XRam.cs
src/OpenAL/Extensions/Silk.NET.OpenAL.Extensions.EXT/Capture.cs
src/OpenAL/Silk.NET.OpenAL/AL/AL.cs
src/OpenAL/Silk.NET.OpenAL/ALC/ALContext.cs

Fixes various bugs in OpenAL.
1.X
https://discordapp.com/channels/521092042781229087/607634593201520651/699292696434573408

More OpenAL fixes

---

documentation/proposals/Proposal - Contexts.md

- Adds IGLContext proposal for 1.X if approved
- If approved, ties each context to a GL instance.
1.X and 2.0
Links go here.

[1.X/2.0] Context proposals

---

src/Core/Silk.NET.Core/Core1.0/Native/FuncPtr.cs
src/Windowing/Silk.NET.GLFW/Glfw.cs
src/Windowing/Silk.NET.Windowing.Common/Interfaces/IViewProperties.cs
src/Windowing/Silk.NET.Windowing.Common/ViewOptions.cs
src/Windowing/Silk.NET.Windowing.Common/WindowOptions.cs
src/Windowing/Silk.NET.Windowing.Desktop/GlfwWindow.cs

Fixes a couple of bugs that have popped up recently.
1.X
Fixes #168 
Fixes #169
We should probably give the cross-boundary exception thing another lookover and ensure we've littered ThrowExceptions calls to a sufficient extent, but for now I think we've covered it to a minimal extent.

[1.X] Desktop Windowing Fixes & Improvements

---

Silk.NET.sln
src/Windowing/Extensions/Silk.NET.Windowing.Extensions.Veldrid/Silk.NET.Windowing.Extensions.Veldrid.csproj
src/Windowing/Extensions/Silk.NET.Windowing.Extensions.Veldrid/VeldridWindow.cs

Adds windowing extensions for using Silk.NET.Windowing in conjunction with Veldrid.
1.X
Links go here.
Used to be NDA, figured I'd release it with <3 for open-source.

[1.X] Veldrid Extensions

---

build/binder_specifications/OpenCL.json
src/Core/Silk.NET.Core/Core1.0/Attributes/ExtensionAttribute.cs
src/Lab/BlankWindow/Program.cs
src/OpenCL/Extensions/Silk.NET.OpenCL.Extensions.AMD/Enums/AMD.gen.cs
src/Vulkan/Silk.NET.Vulkan/Vk.cs
src/Vulkan/Silk.NET.Vulkan/VkExtensionLoader.cs
src/Vulkan/Silk.NET.Vulkan/VkExtensionLoaderSource.cs

Makes extension loading operate independently of CurrentDevice and CurrentInstance
1.X
#180 
I also accidentally reran the generator so we have an up-to-date OpenCL spec now lmao

Vulkan Extension Loader Improvements

---

src/Maths/Silk.NET.Maths/SwizzleOperators.cs

Forgot about these yesterday, sorry about that 😅 
See #201

Downsizing Swizzle operators

---

src/Maths/Silk.NET.Maths/Box2.cs
src/Maths/Silk.NET.Maths/Box3.cs
src/Maths/Silk.NET.Maths/Quaternion.cs
src/Maths/Silk.NET.Maths/Scalar.cs
src/Maths/Silk.NET.Maths/Silk.NET.Maths.csproj
src/Maths/Silk.NET.Maths/SwizzleOperators.cs
src/Maths/Silk.NET.Maths/Vector2.cs
src/Maths/Silk.NET.Maths/Vector3.cs
src/Maths/Silk.NET.Maths/Vector4.cs

Better hash codes

---

Silk.NET.sln
examples/CSharp/Tutorial 3.3 - Specular Lighting/BufferObject.cs
examples/CSharp/Tutorial 3.3 - Specular Lighting/Camera.cs
examples/CSharp/Tutorial 3.3 - Specular Lighting/MathHelper.cs
examples/CSharp/Tutorial 3.3 - Specular Lighting/Program.cs
examples/CSharp/Tutorial 3.3 - Specular Lighting/Shader.cs
examples/CSharp/Tutorial 3.3 - Specular Lighting/Texture.cs
examples/CSharp/Tutorial 3.3 - Specular Lighting/Transform.cs
examples/CSharp/Tutorial 3.3 - Specular Lighting/Tutorial 3.3 - Specular Lighting.csproj
examples/CSharp/Tutorial 3.3 - Specular Lighting/VertexArrayObject.cs
examples/CSharp/Tutorial 3.3 - Specular Lighting/lighting.frag
examples/CSharp/Tutorial 3.3 - Specular Lighting/shader.frag
examples/CSharp/Tutorial 3.3 - Specular Lighting/shader.vert

Add a Tutorial 3.3 project to the examples for specular lighting to loosely follow chapter 13.6 of learnopengl
This builds on top of the work done in #229 but in its own split from the master branch, 3.2 tutorial should be reviewed first as any changes to the project for 3.2 I would need to reflect here too.

Create Tutorial 3.3 for Specular Lighting

---

Silk.NET.sln
examples/CSharp/Tutorial 3.4 - Materials/BufferObject.cs
examples/CSharp/Tutorial 3.4 - Materials/Camera.cs
examples/CSharp/Tutorial 3.4 - Materials/MathHelper.cs
examples/CSharp/Tutorial 3.4 - Materials/Program.cs
examples/CSharp/Tutorial 3.4 - Materials/Shader.cs
examples/CSharp/Tutorial 3.4 - Materials/Texture.cs
examples/CSharp/Tutorial 3.4 - Materials/Transform.cs
examples/CSharp/Tutorial 3.4 - Materials/Tutorial 3.4 - Materials.csproj
examples/CSharp/Tutorial 3.4 - Materials/VertexArrayObject.cs
examples/CSharp/Tutorial 3.4 - Materials/lighting.frag
examples/CSharp/Tutorial 3.4 - Materials/shader.frag
examples/CSharp/Tutorial 3.4 - Materials/shader.vert

Add a Tutorial 3.4 project for using Material and Lighting structs within the lighting shader to demonstrate how these properties can be passed in through code. Loosely follows chapter 14 of learnopengl.

Create Tutorial 3.4 to demonstrate use of Materials in lighting shader

---

examples/CSharp/Tutorial 2.1 - Co-ordinate Systems/Program.cs
src/Windowing/Extensions/Silk.NET.Windowing.Extensions.Veldrid/VeldridWindow.cs
src/Windowing/Silk.NET.Windowing.Common/Interfaces/IView.cs
src/Windowing/Silk.NET.Windowing.Common/Interfaces/IWindowProperties.cs
src/Windowing/Silk.NET.Windowing.Common/WindowOptions.cs
src/Windowing/Silk.NET.Windowing.Desktop/GlfwWindow.cs

Attempt to add the Time property to Window class, wrapping around glfwGetTime.
Closes #220

Add Time property to Window

---

examples/CSharp/Tutorial 2.1 - Co-ordinate Systems/MathHelper.cs
examples/CSharp/Tutorial 2.1 - Co-ordinate Systems/Program.cs
examples/CSharp/Tutorial 2.2 - Camera/MathHelper.cs
examples/CSharp/Tutorial 2.2 - Camera/Program.cs
examples/CSharp/Tutorial 3.1 - Ambient Lighting/Camera.cs
examples/CSharp/Tutorial 3.1 - Ambient Lighting/MathHelper.cs
examples/CSharp/Tutorial 3.1 - Ambient Lighting/Program.cs
examples/CSharp/Tutorial 3.2 - Diffuse Lighting/Camera.cs
examples/CSharp/Tutorial 3.2 - Diffuse Lighting/Program.cs
examples/CSharp/Tutorial 3.3 - Specular Lighting/Camera.cs
examples/CSharp/Tutorial 3.3 - Specular Lighting/MathHelper.cs
examples/CSharp/Tutorial 3.3 - Specular Lighting/Program.cs
examples/CSharp/Tutorial 3.4 - Materials/Camera.cs
examples/CSharp/Tutorial 3.4 - Materials/MathHelper.cs
examples/CSharp/Tutorial 3.4 - Materials/Program.cs

The Camera controls in the tutorial projects are a bit clunky at the moment. They can be improved by swapping the cursor mode to raw input and tweaking the sensitivity settings to give a smoother level of control over movement through the scene.

Improve Tutorial Camera Controls

---

azure-pipelines-cd.yml
azure-pipelines.yml
global.json

See https://devblogs.microsoft.com/dotnet/announcing-net-5-0-preview-7/

Upgrade to .Net 5 Preview 7

---

.github/workflows/build.yml
.github/workflows/label.yml

Fixes Azure DevOps being a weenie
Links go here.
Still uses AzDO for package storage, as I don't wanna change the feed for experimental consumers.

Move to GitHub for CI and CD

---

CODEOWNERS
README.md

We will miss you, Void.

---

src/OpenXR/Silk.NET.OpenXR/XR.cs

Fixes Add(ICollection<string>, byte*) adding empty strings

Fix Add(ICollection<string>, byte*) adding empty strings

---

src/Core/Silk.NET.SilkTouch/BoolMarshaller.cs
src/Core/Silk.NET.SilkTouch/DelegateMarshaller.cs
src/Core/Silk.NET.SilkTouch/Diagnostics.cs
src/Core/Silk.NET.SilkTouch/MarshalBuilder.cs
src/Core/Silk.NET.SilkTouch/MarshalContext.cs
src/Core/Silk.NET.SilkTouch/Middleware.cs
src/Core/Silk.NET.SilkTouch/NativeApiGenerator.cs
src/Core/Silk.NET.SilkTouch/ParameterInitMiddleware.cs
src/Core/Silk.NET.SilkTouch/PinMiddleware.cs
src/Core/Silk.NET.SilkTouch/PinObjectMarshaller.cs
src/Core/Silk.NET.SilkTouch/SpanMarshaller.cs
src/Core/Silk.NET.SilkTouch/StringMarshaller.cs

SilkTouch improvements

---

src/Core/Silk.NET.Core/Attributes/UnmanagedTypeAttribute.cs
src/Core/Silk.NET.Core/Native/UnmanagedType.cs
src/Core/Silk.NET.SilkTouch/BoolMarshaller.cs
src/Core/Silk.NET.SilkTouch/Diagnostics.cs
src/Core/Silk.NET.SilkTouch/MarshalContext.cs
src/Core/Silk.NET.SilkTouch/NativeApiGenerator.cs
src/Core/Silk.NET.SilkTouch/Silk.NET.SilkTouch.csproj
src/Core/Silk.NET.SilkTouch/StringMarshaller.cs
src/OpenAL/Extensions/Silk.NET.OpenAL.Extensions.Creative/EffectExtension.cs
src/OpenAL/Extensions/Silk.NET.OpenAL.Extensions.Creative/XRam.cs
src/OpenAL/Silk.NET.OpenAL/AL/AL.cs

New Marshaller API

---

src/Core/Silk.NET.Core/Native/ConcurrentDictionaryVTable.cs
src/Core/Silk.NET.Core/Native/IVTable.cs
src/Core/Silk.NET.Core/Native/NativeApiContainer.cs
src/Core/Silk.NET.SilkTouch/Diagnostics.cs
src/Core/Silk.NET.SilkTouch/MarshalContext.cs
src/Core/Silk.NET.SilkTouch/NativeApiGenerator.cs
src/Core/Silk.NET.SilkTouch/PinObjectMarshaller.cs

- massively reduces GCUtil footprint (closes #272)
- abstracts VTable implementation (foundation for #289)

Core Abstractions

---

.editorconfig
src/Core/Silk.NET.Core/Native/NativeApiContainer.cs
src/Core/Silk.NET.SilkTouch/NativeApiGenerator.cs

Generate VTable class

---

.github/workflows/build.yml
.github/workflows/deploy.yml
global.json
src/Core/Silk.NET.SilkTouch/NativeApiGenerator.cs
src/Core/Silk.NET.SilkTouch/Silk.NET.SilkTouch.csproj

This PR would require RC1+ to be installed for the project to build, because SilkTouch does.

Update to .Net 5 RC1

---

build/props/common.props
src/Lab/MonitorPlayground/Program.cs
src/Windowing/Silk.NET.Windowing.Common/Interfaces/IWindow.cs
src/Windowing/Silk.NET.Windowing.Common/WindowExtensions.cs
src/Windowing/Silk.NET.Windowing.Desktop/GlfwWindow.cs

Said it all in the title
https://discordapp.com/channels/521092042781229087/607634593201520651/756873490212192325
Also updates release notes for 1.7.

Add BorderSize, GetFullSize(), and Centre() for IWindow

---

src/Lab/GenericMaths/Program.cs
src/Maths/Silk.NET.Maths.GenericsGenerator/Generator.cs
src/Maths/Silk.NET.Maths.GenericsGenerator/OperationWalker.cs
src/Maths/Silk.NET.Maths.GenericsGenerator/ValueTypes/LiteralValue.cs

This PR will add multiple options, including:
- Configuring type specialization (Specialized Types, Generic type, both)
- Name Minification

Math Generator options

---

src/Core/Silk.NET.SilkTouch/StringMarshaller.cs

Also introduces a constant for every allocated slot.
Also made me realize that I just made a quick patch to lower Slot numbers, but the slots are actually still allocated internally, just not at runtime & in memory.

Fixup String marshalling

---

src/Maths/Silk.NET.Maths/Silk.NET.Maths.csproj

We already shipped this :eyes:

Import common in maths

---

src/Core/Silk.NET.Core/Attributes/InjectAttribute.cs
src/Core/Silk.NET.SilkTouch/MarshalContext.cs
src/Core/Silk.NET.SilkTouch/Middlewares/InjectMiddleware.cs
src/Core/Silk.NET.SilkTouch/Middlewares/ParameterInitMiddleware.cs
src/Core/Silk.NET.SilkTouch/NativeApiGenerator.cs
src/Core/Silk.NET.SilkTouch/Silk.NET.SilkTouch.csproj
src/Lab/TestLib/Class1.cs

SilkTouch staging & injecting

---

src/Core/Silk.NET.SilkTouch/NameGenerator.cs
src/Core/Silk.NET.SilkTouch/NativeApiGenerator.cs
src/Core/Silk.NET.SilkTouch/NativeContextOverrides/PInvokeNativeContextOverride.cs
src/Core/Silk.NET.SilkTouch/VTableGeneration.cs

Minify Trees

---

src/Lab/BlankWindow/Program.cs

Correctly implements the image loading logic for the `favicon.png`.

Fixes image loading logic.

---

src/Core/Silk.NET.Core/Native/GlobalMemory.cs

Handle allocations of size less than 0

---

src/Maths/Silk.NET.Maths.Tests/PowIntTests.cs
src/Maths/Silk.NET.Maths/Scalar.BaseOps.cs
src/Maths/Silk.NET.Maths/Scalar.Constants.cs
src/Maths/Silk.NET.Maths/Scalar.Inverse.cs
src/Maths/Silk.NET.Maths/Scalar.MathFPort.cs

Fix the (s)byte code

---

.github/workflows/build.yml

As discussed on discord, only publish experimental packages on push to main or release/*

Limit Experimental Packages

---

.github/workflows/build.yml
.github/workflows/deploy.yml
global.json
src/Core/Silk.NET.SilkTouch/NativeApiGenerator.cs
src/Core/Silk.NET.SilkTouch/NativeContextOverrideGeneration.cs
src/Core/Silk.NET.SilkTouch/Silk.NET.SilkTouch.csproj
src/Core/Silk.NET.SilkTouch/SyntaxReceiver.cs
src/Lab/TestLib/Class1.cs
src/Lab/TestLib/TestClass2-1.cs
src/Lab/TestLib/TestClass2-2.cs
src/Lab/TestLib/TestClass2-3.cs

Start of multi-partials

---

CONTRIBUTING.md
README.md
build/props/common.props
src/Core/Silk.NET.SilkTouch/Diagnostics.cs

- Allows csprojs to override `PackageTags` and `Description`
- Updates some links to the new repo

Package Changes

---

src/Windowing/Silk.NET.Windowing.Glfw/GlfwWindow.cs

Closes #453 
It's literally just one LOC.

Fix GLFW not respecting the start-up window state (closes #453)

---

src/Lab/VulkanTriangle/HelloTriangleApplication.cs

The current Vulkan triangle sample code has some problems:
1. The Vulkan validation layer issues some warnings/errors
2. Resizing crashes the app
This PR will:
- fix the warnings/errors pointed out in the validation layers
- make window resizing work
- continously update window when resizing, as this removes artifacts when resizing
The changes more or less follow the Vulkan Tutorial which is already the base for this code until Swapchain recreation:
https://vulkan-tutorial.com/Drawing_a_triangle/Swap_chain_recreation

Enhanced vulkan triangle app

---

src/Windowing/Silk.NET.GLFW/GlfwNativeWindow.cs

On x86 platform, the function GetWindowLongPtr  is not available causing an exception in the GLFX windowing backend.
-
The problem is described on pinvoke here: https://www.pinvoke.net/default.aspx/user32.getwindowlongptr
The proposed fix is derived from the proposed implementation at pinvoke, adapted to use nint instead of IntPtr to follow the code style of Silk.NET

Fix GetWindowLongPtr on x86

---

src/Lab/Experiments/ImGuiVulkan/Lib/ImGuiController.cs

The lab vulkan/imgui controller had a bug that prevented designated fonts from correctly loaded (also was failing silently.)
This change only moves context creation up a bit, despite github showing a large diff for some reason :/

Fix custom font loading

---

src/Core/Silk.NET.Core/Native/GlobalMemory.cs

Remove Span<T> from the call chain in GlobalMemory

---

src/Lab/Experiments/VulkanTriangle/HelloTriangleApplication.cs

The validation layers cause a crash on my computer, proposed implementation more similar to https://github.com/KhronosGroup/Vulkan-Samples/blob/96dc1b3d729a743b7bb1caf5b9a631a5e684538b/samples/api/hpp_hello_triangle/hpp_hello_triangle.cpp#L135
https://github.com/dotnet/Silk.NET/pull/587

Linux fix for Silk.NET Vulkan Triangle experiment.

---

src/Lab/Experiments/README.md

The lab applications are not examples.

The lab applications are not examples.

---

build/nuke/Projects.cs
src/Lab/Experiments/TriangleDroid/Resources/Resource.Designer.cs
src/Lab/Experiments/TriangleDroid/TriangleDroid.csproj
src/Lab/Experiments/TriangleDroidUvExperiment/MainActivity.cs
src/Lab/Experiments/TriangleDroidUvExperiment/Resources/Resource.Designer.cs
src/Lab/Experiments/TriangleDroidUvExperiment/TriangleDroidUvExperiment.csproj
src/Lab/Experiments/TriangleIOS/Main.cs
src/Lab/Experiments/TriangleIOS/TriangleIOS.csproj

Stop always generating & building legacy solutions

---

documentation/proposals/Proposal - Bitwise - Scalar.md
documentation/proposals/Proposal - Vectorization - SIMD.md

Minor proposal changes

---

build/props/common.props
src/Core/Silk.NET.BuildTools/Silk.NET.BuildTools.csproj

This is the .NET Conf 2021 Update (v2.10.1)

---

.github/workflows/publish-site.yml

Fix failing CI

---

.github/workflows/codeowners.yml
CODEOWNERS

- Adds a codeowner validator 
- Tries to fix codeowners

CODEOWNERS fixes

---

documentation/proposals/Proposal - Vectorization - SIMD.md

Typo fixed

---

src/Input/Silk.NET.Input.Common/Structs/ScrollWheel.cs
src/Input/Silk.NET.Input.Sdl/SdlInputContext.cs
src/Input/Silk.NET.Input.Sdl/SdlKeyboard.cs
src/Windowing/Silk.NET.Windowing.Sdl/SdlView.cs

This PR fixes input events not being registered correctly and the window hanging problem from issue #698.

Fix multiple input-related problems on SDL

---

examples/CSharp/OpenGL Demos/ImGui/Program.cs

"The render funciton" changed to "The render function"

Fixed a typo in a comment

---

src/Input/Silk.NET.Input.Common/Interfaces/IKeyboard.cs
src/Input/Silk.NET.Input.Glfw/GlfwKeyboard.cs
src/Input/Silk.NET.Input.Sdl/SdlKeyboard.cs

Add the ability to change the system clipboard
#732

Implement ClipboardText on IKeyboard

---

Silk.NET.sln
src/Core/Silk.NET.Core/Native/SilkMarshal.cs
src/Lab/Experiments/NonAsciiWindow/NonAsciiWindow.csproj
src/Lab/Experiments/NonAsciiWindow/Program.cs

Ensure we allocate enough bytes for non-ASCII strings (#736)

---

src/OpenAL/Extensions/Silk.NET.OpenAL.Extensions.Creative/EnumerateAll.cs
src/OpenAL/Extensions/Silk.NET.OpenAL.Extensions.EXT/CaptureEnumerationEnumeration.cs
src/OpenAL/Extensions/Silk.NET.OpenAL.Extensions.Enumeration/Enumeration.cs
src/OpenAL/Silk.NET.OpenAL.Tests/GetStringListTests.cs
src/OpenAL/Silk.NET.OpenAL.Tests/RunnableInDebugOnlyAttribute.cs
src/OpenAL/Silk.NET.OpenAL.Tests/Silk.NET.OpenAL.Tests.csproj

As reported by LoadingNinja in Discord

Fix a SymbolLoadingException in GetStringList

---

README.md

Adds a bit to the readme about installing nuke for clarity

Add nuke install instructions

---

src/Vulkan/Silk.NET.Vulkan/Vk.cs

It adds the Vulkan 1.3 Version Property
nop
used the opportunity for a easy contribution LOL

Add a Vulkan 1.3 Version Property

---

src/Microsoft/Silk.NET.DXGI/DXGI.cs

Adds the DXGI_CREATE_FACTORY_DEBUG Constant to DXGI
Fixes https://github.com/dotnet/Silk.NET/issues/722
None

Add DXGI_CREATE_FACTORY_DEBUG Constant to DXGI

---

src/OpenGL/Extensions/Silk.NET.OpenGL.Extensions.ImGui/ImGuiController.cs
src/OpenGL/Extensions/Silk.NET.OpenGL.Extensions.ImGui/PublicAPI/net5.0/PublicAPI.Unshipped.txt
src/OpenGL/Extensions/Silk.NET.OpenGL.Extensions.ImGui/PublicAPI/netcoreapp3.1/PublicAPI.Unshipped.txt
src/OpenGL/Extensions/Silk.NET.OpenGL.Extensions.ImGui/PublicAPI/netstandard2.0/PublicAPI.Unshipped.txt
src/OpenGL/Extensions/Silk.NET.OpenGL.Extensions.ImGui/PublicAPI/netstandard2.1/PublicAPI.Unshipped.txt
src/OpenGL/Extensions/Silk.NET.OpenGL.Legacy.Extensions.ImGui/PublicAPI/net5.0/PublicAPI.Unshipped.txt
src/OpenGL/Extensions/Silk.NET.OpenGL.Legacy.Extensions.ImGui/PublicAPI/netcoreapp3.1/PublicAPI.Unshipped.txt
src/OpenGL/Extensions/Silk.NET.OpenGL.Legacy.Extensions.ImGui/PublicAPI/netstandard2.0/PublicAPI.Unshipped.txt
src/OpenGL/Extensions/Silk.NET.OpenGL.Legacy.Extensions.ImGui/PublicAPI/netstandard2.1/PublicAPI.Unshipped.txt
src/OpenGL/Extensions/Silk.NET.OpenGLES.Extensions.ImGui/PublicAPI/net5.0/PublicAPI.Unshipped.txt
src/OpenGL/Extensions/Silk.NET.OpenGLES.Extensions.ImGui/PublicAPI/netcoreapp3.1/PublicAPI.Unshipped.txt
src/OpenGL/Extensions/Silk.NET.OpenGLES.Extensions.ImGui/PublicAPI/netstandard2.0/PublicAPI.Unshipped.txt
src/OpenGL/Extensions/Silk.NET.OpenGLES.Extensions.ImGui/PublicAPI/netstandard2.1/PublicAPI.Unshipped.txt

Before now we would lazily create an ImGui context and assume nothing else would tamper with ImGui state, along with never destroying our own context once Dispose was called
https://discord.com/channels/521092042781229087/587346162802229298/965745680503164968

ImGui: Better disposal and multiple ImGuiController handling

---

tests/Silk.NET.SilkTouch.Emitter.Tests/EmitterFieldTests.cs

Thought there would be more. I hope the merge works out.

Move all CreateEmitter() tests to Transform(...)

---

tests/Silk.NET.SilkTouch.Emitter.Tests/EmitterFieldTests.cs

Forgot to write these initially, so figured I'd do it now.

Field Tests

---

CODEOWNERS

Comment out Perksey in CODEOWNERS

---

CODEOWNERS

Remove Perksey from CODEOWNERS for 3.0

---

website/index.cshtml

Fixes a type of the landing page of the website "commecial" to "commercial"

start of typo correction on website

---

src/Core/Silk.NET.Core/Silk.NET.Core.csproj
src/Lab/Experiments/PrototypeStructChaining/PrototypeStructChaining/PrototypeStructChaining.csproj

Update DependencyModel to support single file mode
Fixes #958

Fix NativeAOT

---

src/OpenGL/Extensions/Silk.NET.OpenGL.Extensions.ImGui/Silk.NET.OpenGL.Extensions.ImGui.csproj
src/OpenGL/Extensions/Silk.NET.OpenGL.Legacy.Extensions.ImGui/Silk.NET.OpenGL.Legacy.Extensions.ImGui.csproj
src/OpenGL/Extensions/Silk.NET.OpenGLES.Extensions.ImGui/Silk.NET.OpenGLES.Extensions.ImGui.csproj

Updates all ImGui extensions to the latest revision of ImGui.NET
Also puts all of them in sync, as before one of the extensions was a different version to the other 2

Update ImGui.NET to 1.87.3

---

src/Maths/Silk.NET.Maths.Tests/Vector3Tests.cs
src/Maths/Silk.NET.Maths.Tests/Vector4Tests.cs

Remove first param in `Vector4Tests.Vector4CopyToTest`

---

nuget.config

Fix compilation
https://canary.discord.com/channels/521092042781229087/587346162802229298/1007441794394488954

Add nuget.config to fix compilation

---

tests/Silk.NET.Maths.Tests/Vector3Tests.cs
tests/Silk.NET.Maths.Tests/Vector4Tests.cs

Backport math fixes

---

src/Windowing/Silk.NET.Windowing.Common/Internals/ViewImplementationBase.cs

This would cause issues on the SDL backend
https://discord.com/channels/521092042781229087/607634593201520651/1008114269688176681

Throw exception when you try to run `Reset` inside of the render loop

---

src/Core/Silk.NET.Core/Contexts/INativeWindow.cs
src/Core/Silk.NET.Core/PublicAPI/net5.0/PublicAPI.Unshipped.txt
src/Core/Silk.NET.Core/PublicAPI/net6.0/PublicAPI.Unshipped.txt
src/Core/Silk.NET.Core/PublicAPI/netcoreapp3.1/PublicAPI.Unshipped.txt
src/Core/Silk.NET.Core/PublicAPI/netstandard2.0/PublicAPI.Unshipped.txt
src/Core/Silk.NET.Core/PublicAPI/netstandard2.1/PublicAPI.Unshipped.txt
src/Windowing/Silk.NET.GLFW/GlfwNativeWindow.cs
src/Windowing/Silk.NET.SDL/SdlNativeWindow.cs

Adds a specific DXHandle property on `INativeWindow` for use with DXVK-native
https://discord.com/channels/521092042781229087/587346162802229298/1012052207161589800

Add DXHandle property on `INativeWindow`

---

website/docs/hlu/troubleshooting.md

Documents that we need the Visual C++ redist
https://github.com/dotnet/Silk.NET/issues/576

Document Visual C++ redist requirement

---

README.md

Add beyley to maintainers

---

src/Windowing/Silk.NET.SDL/SDL.cs
src/Windowing/Silk.NET.SDL/Sdl.gen.cs
src/Windowing/Silk.NET.Windowing.Common/Interfaces/IWindowProperties.cs
src/Windowing/Silk.NET.Windowing.Common/Internals/WindowImplementationBase.cs
src/Windowing/Silk.NET.Windowing.Common/PublicAPI/netstandard2.0/PublicAPI.Unshipped.txt
src/Windowing/Silk.NET.Windowing.Common/PublicAPI/netstandard2.1/PublicAPI.Unshipped.txt
src/Windowing/Silk.NET.Windowing.Common/Structs/WindowOptions.cs
src/Windowing/Silk.NET.Windowing.Glfw/GlfwWindow.cs
src/Windowing/Silk.NET.Windowing.Sdl/SdlWindow.cs

Adding the feature to make GlfwWindow TopMost from options and can be set while the window is running.

Adding TopMost to WindowProperties and GlfwWindow

---

CODEOWNERS

Add Beyley is a code owner of the ImGui OpenGL extensions

Add Beyley is a code owner of the OpenGL subdir

---

src/Windowing/Silk.NET.GLFW/GlfwNativeWindow.cs

DXHandle wasnt set properly on GLFW in some cases
https://discordapp.com/channels/521092042781229087/587346162802229298/1049448081965453313

Fix GLFWNativeWindow DXHandle

---

.github/workflows/test.yml
src/benchmarks/Silk.NET.Maths.Benchmarks/Program.cs

Getting back on track

---

src/generators/Silk.NET.SilkTouch.Emitter/CSharpEmitter.cs
src/generators/Silk.NET.SilkTouch.Scraper/XmlVisitor.cs
src/generators/Silk.NET.SilkTouch.Symbols/ClassSymbol.cs
src/generators/Silk.NET.SilkTouch.Symbols/StructSymbol.cs
src/generators/Silk.NET.SilkTouch.Symbols/SymbolVisitor.cs
src/generators/Silk.NET.SilkTouch.Symbols/TypeSymbol.cs
tests/Silk.NET.SilkTouch.Emitter.Tests/ClassSymbolTests.cs
tests/Silk.NET.SilkTouch.Emitter.Tests/EmitterNamespaceMemberTests.cs
tests/Silk.NET.SilkTouch.Emitter.Tests/EmitterStructMemberFieldsTests.cs
tests/Silk.NET.SilkTouch.Emitter.Tests/EmitterStructTests.cs
tests/Silk.NET.SilkTouch.Emitter.Tests/InternalTypeReferenceTests.cs
tests/Silk.NET.SilkTouch.Scraper.Tests/StructMemberScrapingTests.cs
tests/Silk.NET.SilkTouch.Symbols.Tests/SymbolVisitorTests/StructTests.cs
tests/Silk.NET.SilkTouch.Tests.Common/Fakers.cs
tests/Silk.NET.SilkTouch.TypeResolution.Tests/NameResolverSymbolVisitorTests.cs
tests/Silk.NET.SilkTouch.TypeResolution.Tests/TypeScopeSymbolVisitorTests.cs

- Allow different types on fields
- Unify Member field on type defs
Links go here.

Unify type members

---

src/Core/Silk.NET.BuildTools/Program.cs

Saves me from having to make another config file when doing rapid work on BuildTools or the single task in question
https://discord.com/channels/521092042781229087/587346162802229298/1087119406980665404

BuildTools: Add --profile='' parameter to BuildTools to only do one profile out of the config

---

generator.json
src/WebGPU/Silk.NET.WebGPU/WebGPULibraryNameContainer.cs

Fix search path on Windows for WGPU

---

examples/CSharp/OpenGL Tutorials/Tutorial 4.1 - Model Loading/Model.cs

Work started
Model loading code of tutorial 4.1 copies vertices and uv data float by float instead of assignment of full vector
Links go here.

start of updating assimp usage in tutorial 4.1

---

src/OpenGL/Silk.NET.WGL/WGL.cs

Implements WGL GetApi() 
Closes #1467 
This hardcodes a single name, since this will only ever run on a single platform

Add implementation for GetApi()

---

src/Core/Silk.NET.Core/Native/PinObjectAttribute.cs
src/Core/Silk.NET.SilkTouch/Middlewares/PinObjectMarshaller.cs
src/Core/Silk.NET.SilkTouch/NativeApiGenerator.cs
src/Windowing/Silk.NET.GLFW/Glfw.cs

This allows us to make pinnings dependent on handles as well as the allocated GC slot.
Closes #1544

Add specification of discriminant values for the PinObjectMarshaller

---

website/docs/opengl/c1/1-hello-window.md
website/docs/opengl/sources/1.1-final-result.md
website/docs/opengl/sources/1.2-final-result.md
website/docs/opengl/sources/1.2.2-clear-window.md
website/docs/opengl/sources/1.2.7-finished-setup.md

Changes a parameter name in the documentation to be more descriptive and removes a short explanation of what it is.
None

Rename dt parameter to deltaTime

---

src/Core/Silk.NET.Core/Loader/DefaultPathResolver.cs

Reduce string allocations in Path-related calls

---

build/props/common.props

Allow use of MSBuild without Git

---

.github/workflows/moltenvk.yml
build/nuke/Native/Core.cs

Updated MoltenVK binaries

---

src/Vulkan/Silk.NET.Vulkan/Vk.cs

fix IsDeviceExtensionPresent 
[Links go here.](https://discord.com/channels/521092042781229087/607634593201520651/1162059376790601758)
Work checked on iOS and macOS.

start of fix IsDeviceExtensionPresent

---

src/Windowing/Silk.NET.Windowing.Glfw/GlfwWindow.cs
src/Windowing/Silk.NET.Windowing.Sdl/SdlWindow.cs

Add UTF-8 file path support for GLFW window and SDL window.
#1809

Support UTF-8 file path

---

documentation/proposals/(On hold) Proposal - Input maps.md
documentation/proposals/Proposal - Multi-Backend Input.md

some new features and a little changing on the structure.
in reality, it's not finished, i'm posting here to have a better revision and discursion about the features that i'm trying to propose
(also some helps with possible english mistakes)
all feedback will be very well received

extra features to the input proposal

---

examples/CSharp/OpenGL Tutorials/Tutorial 1.1 - Hello Window/Program.cs
examples/CSharp/OpenGL Tutorials/Tutorial 1.2 - Hello quad/Program.cs
examples/CSharp/OpenGL Tutorials/Tutorial 1.3 - Textures/Program.cs
examples/CSharp/OpenGL Tutorials/Tutorial 1.4 - Abstractions/Program.cs
examples/CSharp/OpenGL Tutorials/Tutorial 1.5 - Transformations/Program.cs
examples/CSharp/OpenGL Tutorials/Tutorial 2.1 - Co-ordinate Systems/Program.cs
examples/CSharp/OpenGL Tutorials/Tutorial 2.2 - Camera/Program.cs
examples/CSharp/OpenGL Tutorials/Tutorial 3.1 - Ambient Lighting/Program.cs
examples/CSharp/OpenGL Tutorials/Tutorial 3.2 - Diffuse Lighting/Program.cs
examples/CSharp/OpenGL Tutorials/Tutorial 3.3 - Specular Lighting/Program.cs
examples/CSharp/OpenGL Tutorials/Tutorial 3.4 - Materials/Program.cs
examples/CSharp/OpenGL Tutorials/Tutorial 3.5 - Lighting Maps/Program.cs
examples/CSharp/OpenGL Tutorials/Tutorial 4.1 - Model Loading/Program.cs
examples/CSharp/OpenGL Tutorials/Tutorial 4.1 - Model Loading/Tutorial 4.1 - Model Loading.csproj

Update Viewport on resize in all of the GL tutorials.

---

src/Core/Silk.NET.Core/Native/SilkMarshal.cs
src/Core/Silk.NET.SilkTouch/Middlewares/StringMarshaller.cs
src/Windowing/Silk.NET.GLFW/GlfwProvider.cs

Fix AVE in PtrToString on .NET 8 & remove unnecessary marshalling

---

src/Input/Silk.NET.Input.Glfw/GlfwJoystick.cs
src/Windowing/Silk.NET.Windowing.Sdl/SdlWindow.cs

Fire GLFW joystick events

---

build/nuke/Native/MoltenVK.cs

For #1993.
cc @Perksey @Beyley

Fix MoltenVK native build failures due to file overwrite.

---

.github/workflows/assimp.yml
.github/workflows/build.yml
.github/workflows/dxvk.yml
.github/workflows/glfw.yml
.github/workflows/moltenvk.yml
.github/workflows/public-api.yml
.github/workflows/sdl2.yml
.github/workflows/shaderc.yml
.github/workflows/spirv-cross.yml
.github/workflows/spirv-reflect.yml
.github/workflows/swiftshader.yml
.github/workflows/vkd3d.yml
.github/workflows/vulkan-loader.yml
.github/workflows/wgpu.yml

The latter only matches up to the first /.

Fix filters in workflows to use ** instead of * where appropriate.

---

README.md

Correcting some versions, removing bad instructions (recursive clone), removing some duplication, and minor formatting.

Some minor README.md corrections.

---

build/props/common.props

Also change RepositoryUrl to have the `.git` extension. I don't know if this actually helps anything, but it seems to be the recommended practice, so better stay on the golden path?

Set `PublishRepositoryUrl` and `EmbedUntrackedSources` for Source Link.

---

build/nuke/Native/MoltenVK.cs

* Build and package binaries for tvOS.
* Strip and re-sign macOS binaries.

Some MoltenVK packaging improvements.

---

src/Input/Silk.NET.Input.Glfw/GlfwJoystick.cs

Fixes the mapping of the Joystick Hat position.
Links go here.

Glfw joystick hat mapping

---

sources/SDL/SDL/SdlContext.cs

Fix a bug reported by @joskuijpers

[3.0] Fix SdlContext throwing for errors

---

README.md

ZEISS getting in touch has made me aware that this is quite out of date now.

Update maintainers list in README
